In [157]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly as plty
import math
import geoip2.database
from user_agents import parse

In [66]:

df = pd.read_csv("./data/int/cybersecurity_attacks.csv")

In [67]:
df

,Timestamp,Source IP Address,Destination IP Address,Source Port,Destination Port,Protocol,Packet Length,Packet Type,Traffic Type,Payload Data,...,Action Taken,Severity Level,User Information,Device Information,Network Segment,Geo-location Data,Proxy Information,Firewall Logs,IDS/IPS Alerts,Log Source
0,2023-05-30 06:33:58,103.216.15.12,84.9.164.252,31225,17616,ICMP,503,Data,HTTP,Qui natus odio asperiores nam. Optio nobis ius...,...,Logged,Low,Reyansh Dugal,Mozilla/5.0 (compatible; MSIE 8.0; Windows NT ...,Segment A,"Jamshedpur, Sikkim",150.9.97.135,Log Data,NaN,Server
1,2020-08-26 07:08:30,78.199.217.198,66.191.137.154,17245,48166,ICMP,1174,Data,HTTP,Aperiam quos modi officiis veritatis rem. Omni...,...,Blocked,Low,Sumer Rana,Mozilla/5.0 (compatible; MSIE 8.0; Windows NT ...,Segment B,"Bilaspur, Nagaland",NaN,Log Data,NaN,Firewall
2,2022-11-13 08:23:25,63.79.210.48,198.219.82.17,16811,53600,UDP,306,Control,HTTP,Perferendis sapiente vitae soluta. Hic delectu...,...,Ignored,Low,Himmat Karpe,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,Segment C,"Bokaro, Rajasthan",114.133.48.179,Log Data,Alert Data,Firewall
3,2023-07-02 10:38:46,163.42.196.10,101.228.192.255,20018,32534,UDP,385,Data,HTTP,Totam maxime beatae expedita explicabo porro l...,...,Blocked,Medium,Fateh Kibe,Mozilla/5.0 (Macintosh; PPC Mac OS X 10_11_5; ...,Segment B,"Jaunpur, Rajasthan",NaN,NaN,Alert Data,Firewall
4,2023-07-16 13:11:07,71.166.185.76,189.243.174.238,6131,26646,TCP,1462,Data,DNS,Odit nesciunt dolorem nisi iste iusto. Animi v...,...,Blocked,Low,Dhanush Chad,Mozilla/5.0 (compatible; MSIE 5.0; Windows NT ...,Segment C,"Anantapur, Tripura",149.6.110.119,NaN,Alert Data,Firewall
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39995,2023-05-26 14:08:42,26.36.109.26,121.100.75.240,31005,6764,UDP,1428,Control,HTTP,Quibusdam ullam consequatur consequuntur accus...,...,Logged,Medium,Adira Madan,Mozilla/5.0 (iPad; CPU iPad OS 14_2_1 like Mac...,Segment A,"Nashik, Manipur",NaN,Log Data,Alert Data,Firewall
39996,2023-03-27 00:38:27,17.21.163.81,196.108.134.78,2553,28091,UDP,1184,Control,HTTP,Quaerat neque esse. Animi expedita natus commo...,...,Logged,High,Rati Dara,Mozilla/5.0 (Windows; U; Windows 98; Win 9x 4....,Segment C,"Vadodara, Mizoram",60.51.30.46,Log Data,NaN,Firewall
39997,2022-03-31 01:45:49,162.35.217.57,98.107.0.15,22505,25152,UDP,1043,Data,DNS,Enim at aspernatur illum. Saepe numquam eligen...,...,Blocked,Low,Samiha Joshi,Mozilla/5.0 (Windows; U; Windows NT 4.0) Apple...,Segment C,"Mahbubnagar, Himachal Pradesh",NaN,Log Data,Alert Data,Server
39998,2023-09-22 18:32:38,208.72.233.205,173.79.112.252,20013,2703,UDP,483,Data,FTP,Officiis dolorem sed harum provident earum dis...,...,Ignored,Low,Rasha Chauhan,Mozilla/5.0 (X11; Linux i686) AppleWebKit/536....,Segment B,"Rourkela, Arunachal Pradesh",137.76.130.8,Log Data,NaN,Server
39999,2023-10-10 11:59:52,14.102.21.108,109.198.45.7,50137,55575,ICMP,1175,Control,HTTP,Eligendi omnis voluptate nihil voluptatibus do...,...,Logged,Medium,Zaina Kumar,Mozilla/5.0 (iPod; U; CPU iPhone OS 3_0 like M...,Segment A,"Pudukkottai, West Bengal",112.169.115.139,Log Data,Alert Data,Firewall

In [68]:
df.describe()

        Source Port  Destination Port  Packet Length  Anomaly Scores
count  40000.000000      40000.000000   40000.000000    40000.000000
mean   32970.356450      33150.868650     781.452725       50.113473
std    18560.425604      18574.668842     416.044192       28.853598
min     1027.000000       1024.000000      64.000000        0.000000
25%    16850.750000      17094.750000     420.000000       25.150000
50%    32856.000000      33004.500000     782.000000       50.345000
75%    48928.250000      49287.000000    1143.000000       75.030000
max    65530.000000      65535.000000    1500.000000      100.000000

In [69]:
df.shape

(40000, 25)

In [ ]:
df.isna().sum()

In [70]:
df.columns

Index(['Timestamp', 'Source IP Address', 'Destination IP Address',
       'Source Port', 'Destination Port', 'Protocol', 'Packet Length',
       'Packet Type', 'Traffic Type', 'Payload Data', 'Malware Indicators',
       'Anomaly Scores', 'Alerts/Warnings', 'Attack Type', 'Attack Signature',
       'Action Taken', 'Severity Level', 'User Information',
       'Device Information', 'Network Segment', 'Geo-location Data',
       'Proxy Information', 'Firewall Logs', 'IDS/IPS Alerts', 'Log Source'],
      dtype='object')

In [71]:
# Count Device Information that occured >= 30 times
df.value_counts("Device Information")[df.value_counts("Device Information") >= 30]

Device Information
Mozilla/5.0 (compatible; MSIE 6.0; Windows NT 6.2; Trident/3.0)     35
Mozilla/5.0 (compatible; MSIE 5.0; Windows 98; Trident/4.1)         34
Mozilla/5.0 (compatible; MSIE 6.0; Windows CE; Trident/4.0)         33
Mozilla/5.0 (compatible; MSIE 5.0; Windows NT 5.2; Trident/4.1)     31
Mozilla/5.0 (compatible; MSIE 7.0; Windows NT 6.0; Trident/3.0)     31
Mozilla/5.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0)     30
Mozilla/5.0 (compatible; MSIE 7.0; Windows 98; Trident/3.1)         30
Mozilla/5.0 (compatible; MSIE 8.0; Windows CE; Trident/3.0)         30
Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 10.0; Trident/4.0)    30
Mozilla/5.0 (compatible; MSIE 8.0; Windows NT 5.1; Trident/3.1)     30
Name: count, dtype: int64

In [159]:
user_agent = parse("Mozilla/5.0 (iPhone; CPU iPhone OS 5_1_1 like Mac OS X) AppleWebKit/533.0 (KHTML, like Gecko) CriOS/51.0.844.0 Mobile/22B509 Safari/533.0")
user_agent.browser.family

'Chrome Mobile iOS'

In [177]:
user_agent2 = parse("Mozilla/5.0 (iPhone; CPU iPhone OS 5_1_1 like Mac OS X) AppleWebKit/533.0 (KHTML, like Gecko) CriOS/51.0.844.0 Mobile/22B509 Safari/533.0")
print(user_agent2.browser)
print(user_agent2.browser.version)
print(user_agent2.browser.version[0])
print(user_agent2.browser.version[1])

Browser(family='Chrome Mobile iOS', version=(51, 0, 844), version_string='51.0.844')
(51, 0, 844)
51
0

In [162]:
df['Browser_family'] = df['Device Information'].apply(lambda x: parse(x).browser.family if parse(x).browser.family is not None else pd.NA)
df.head(2)

,Timestamp,Source IP Address,Destination IP Address,Source Port,Destination Port,Protocol,Packet Length,Packet Type,Traffic Type,Payload Data,...,IDS/IPS Alerts,Log Source,Browser_family,Browser_major,OS_family,OS_major,Device_family,Device_brand,Device_type,is_bot
0,2023-05-30 06:33:58,103.216.15.12,84.9.164.252,31225,17616,ICMP,503,Data,HTTP,Qui natus odio asperiores nam. Optio nobis ius...,...,NaN,Server,IE,9,Windows,8,<NA>,<NA>,PC,False
1,2020-08-26 07:08:30,78.199.217.198,66.191.137.154,17245,48166,ICMP,1174,Data,HTTP,Aperiam quos modi officiis veritatis rem. Omni...,...,NaN,Firewall,IE,8,Windows,Vista,<NA>,<NA>,PC,False

In [178]:
df['Browser_major'] = df['Device Information'].apply(lambda x: parse(x).browser.version[0] if parse(x).browser.version[0] is not None else pd.NA)
df['Browser_minor'] = df['Device Information'].apply(lambda x: parse(x).browser.version[1] if parse(x).browser.version[1] is not None else pd.NA)

In [179]:
df['OS_family'] = df['Device Information'].apply(lambda x: parse(x).os.family if parse(x).os.family is not None else pd.NA)
df.head(2)

,Timestamp,Source IP Address,Destination IP Address,Source Port,Destination Port,Protocol,Packet Length,Packet Type,Traffic Type,Payload Data,...,Log Source,Browser_family,Browser_major,OS_family,OS_major,Device_family,Device_brand,Device_type,is_bot,Browser_minor
0,2023-05-30 06:33:58,103.216.15.12,84.9.164.252,31225,17616,ICMP,503,Data,HTTP,Qui natus odio asperiores nam. Optio nobis ius...,...,Server,IE,9,Windows,8,<NA>,<NA>,PC,False,0
1,2020-08-26 07:08:30,78.199.217.198,66.191.137.154,17245,48166,ICMP,1174,Data,HTTP,Aperiam quos modi officiis veritatis rem. Omni...,...,Firewall,IE,8,Windows,Vista,<NA>,<NA>,PC,False,0

In [ ]:
df['OS_major'] = df['Device Information'].apply(lambda x: parse(x).os.version[0] if parse(x).os.version[0] is not None else pd.NA)
df['OS_minor'] = df['Device Information'].apply(lambda x: parse(x).os.version[1] if parse(x).os.version[1] is not None else pd.NA)
df['OS_patch'] = df['Device Information'].apply(lambda x: parse(x).os.version[2] if parse(x).os.version[2] is not None else pd.NA)

,Timestamp,Source IP Address,Destination IP Address,Source Port,Destination Port,Protocol,Packet Length,Packet Type,Traffic Type,Payload Data,...,Network Segment,Geo-location Data,Proxy Information,Firewall Logs,IDS/IPS Alerts,Log Source,Browser_family,Browser_major,OS_family,OS_major
0,2023-05-30 06:33:58,103.216.15.12,84.9.164.252,31225,17616,ICMP,503,Data,HTTP,Qui natus odio asperiores nam. Optio nobis ius...,...,Segment A,"Jamshedpur, Sikkim",150.9.97.135,Log Data,NaN,Server,IE,9,Windows,8
1,2020-08-26 07:08:30,78.199.217.198,66.191.137.154,17245,48166,ICMP,1174,Data,HTTP,Aperiam quos modi officiis veritatis rem. Omni...,...,Segment B,"Bilaspur, Nagaland",NaN,Log Data,NaN,Firewall,IE,8,Windows,Vista

In [180]:
df['Device_family'] = df['Device Information'].apply(lambda x: parse(x).device.family if parse(x).device.family is not None else pd.NA)

In [ ]:
df['Device_brand'] = df['Device Information'].apply(lambda x: parse(x).device.brand if parse(x).device.brand is not None else pd.NA)

,Timestamp,Source IP Address,Destination IP Address,Source Port,Destination Port,Protocol,Packet Length,Packet Type,Traffic Type,Payload Data,...,Proxy Information,Firewall Logs,IDS/IPS Alerts,Log Source,Browser_family,Browser_major,OS_family,OS_major,Device_family,Device_brand
0,2023-05-30 06:33:58,103.216.15.12,84.9.164.252,31225,17616,ICMP,503,Data,HTTP,Qui natus odio asperiores nam. Optio nobis ius...,...,150.9.97.135,Log Data,NaN,Server,IE,9,Windows,8,<NA>,<NA>
1,2020-08-26 07:08:30,78.199.217.198,66.191.137.154,17245,48166,ICMP,1174,Data,HTTP,Aperiam quos modi officiis veritatis rem. Omni...,...,NaN,Log Data,NaN,Firewall,IE,8,Windows,Vista,<NA>,<NA>

In [181]:
df.head(5)

,Timestamp,Source IP Address,Destination IP Address,Source Port,Destination Port,Protocol,Packet Length,Packet Type,Traffic Type,Payload Data,...,Log Source,Browser_family,Browser_major,OS_family,OS_major,Device_family,Device_brand,Device_type,is_bot,Browser_minor
0,2023-05-30 06:33:58,103.216.15.12,84.9.164.252,31225,17616,ICMP,503,Data,HTTP,Qui natus odio asperiores nam. Optio nobis ius...,...,Server,IE,9,Windows,8,Other,<NA>,PC,False,0
1,2020-08-26 07:08:30,78.199.217.198,66.191.137.154,17245,48166,ICMP,1174,Data,HTTP,Aperiam quos modi officiis veritatis rem. Omni...,...,Firewall,IE,8,Windows,Vista,Other,<NA>,PC,False,0
2,2022-11-13 08:23:25,63.79.210.48,198.219.82.17,16811,53600,UDP,306,Control,HTTP,Perferendis sapiente vitae soluta. Hic delectu...,...,Firewall,IE,9,Windows,8,Other,<NA>,PC,False,0
3,2023-07-02 10:38:46,163.42.196.10,101.228.192.255,20018,32534,UDP,385,Data,HTTP,Totam maxime beatae expedita explicabo porro l...,...,Firewall,Firefox,11,Mac OS X,10,Mac,Apple,PC,False,0
4,2023-07-16 13:11:07,71.166.185.76,189.243.174.238,6131,26646,TCP,1462,Data,DNS,Odit nesciunt dolorem nisi iste iusto. Animi v...,...,Firewall,IE,5,Windows,8,Other,<NA>,PC,False,0

In [135]:
from user_agents import parse as ua_parse

def deviceType(ua_string):
    try:
        if not ua_string or pd.isna(ua_string):
            return pd.NA
        ua = ua_parse(ua_string)           # user_agents.parse -> object with is_mobile/is_tablet/is_pc
        if getattr(ua, "is_mobile", False):
            return "Mobile"
        if getattr(ua, "is_tablet", False):
            return "Tablet"
        if getattr(ua, "is_pc", False):
            return "PC"
        return "Unknown"
    except Exception:
        return "Unknown"

# apply
df['Device_type'] = df['Device Information'].apply(deviceType)
# deviceType("Mozilla/5.0 (iPhone; CPU iPhone OS 5_1_1 like Mac OS X) AppleWebKit/533.0 (KHTML, like Gecko) CriOS/51.0.844.0 Mobile/22B509 Safari/533.0")

In [136]:
df.head(30)

,Timestamp,Source IP Address,Destination IP Address,Source Port,Destination Port,Protocol,Packet Length,Packet Type,Traffic Type,Payload Data,...,Firewall Logs,IDS/IPS Alerts,Log Source,Browser_family,Browser_major,OS_family,OS_major,Device_family,Device_brand,Device_type
0,2023-05-30 06:33:58,103.216.15.12,84.9.164.252,31225,17616,ICMP,503,Data,HTTP,Qui natus odio asperiores nam. Optio nobis ius...,...,Log Data,NaN,Server,IE,9,Windows,8,<NA>,<NA>,PC
1,2020-08-26 07:08:30,78.199.217.198,66.191.137.154,17245,48166,ICMP,1174,Data,HTTP,Aperiam quos modi officiis veritatis rem. Omni...,...,Log Data,NaN,Firewall,IE,8,Windows,Vista,<NA>,<NA>,PC
2,2022-11-13 08:23:25,63.79.210.48,198.219.82.17,16811,53600,UDP,306,Control,HTTP,Perferendis sapiente vitae soluta. Hic delectu...,...,Log Data,Alert Data,Firewall,IE,9,Windows,8,<NA>,<NA>,PC
3,2023-07-02 10:38:46,163.42.196.10,101.228.192.255,20018,32534,UDP,385,Data,HTTP,Totam maxime beatae expedita explicabo porro l...,...,NaN,Alert Data,Firewall,Firefox,11,Mac OS X,10,Mac,Apple,PC
4,2023-07-16 13:11:07,71.166.185.76,189.243.174.238,6131,26646,TCP,1462,Data,DNS,Odit nesciunt dolorem nisi iste iusto. Animi v...,...,NaN,Alert Data,Firewall,IE,5,Windows,8,<NA>,<NA>,PC
5,2022-10-28 13:14:27,198.102.5.160,147.190.155.133,17430,52805,UDP,1423,Data,HTTP,Repellat quas illum harum fugit incidunt exerc...,...,NaN,NaN,Server,Opera,8,Linux,None,<NA>,<NA>,PC
6,2022-05-16 17:55:43,97.253.103.59,77.16.101.53,26562,17416,TCP,379,Data,DNS,Qui numquam inventore repellat ratione fugit o...,...,Log Data,NaN,Server,Opera,9,Linux,None,<NA>,<NA>,PC
7,2023-02-12 07:13:17,11.48.99.245,178.157.14.116,34489,20396,ICMP,1022,Data,DNS,Amet libero optio quidem praesentium libero. E...,...,Log Data,Alert Data,Firewall,Chrome,45,Mac OS X,10,Mac,Apple,PC
8,2023-06-27 11:02:56,49.32.208.167,72.202.237.9,56296,20857,TCP,1281,Control,FTP,Veritatis nihil amet atque molestias aperiam m...,...,Log Data,Alert Data,Server,Chrome,38,Mac OS X,10,Mac,Apple,PC
9,2021-08-15 22:29:04,114.109.149.113,160.88.194.172,37918,50039,UDP,224,Data,HTTP,Consequatur ipsum autem reprehenderit quae. Do...,...,NaN,NaN,Server,Safari,4,Windows,Vista,<NA>,<NA>,PC
10,2022-07-20 13:28:50,177.21.83.200,196.218.124.169,35538,35006,ICMP,661,Data,HTTP,Sequi maxime voluptate ea. Eius officiis eaque...,...,NaN,NaN,Server,Mobile Safari,4,iOS,4,iPod,Apple,Mobile
11,2022-06-26 15:15:50,92.4.25.171,112.43.185.24,10903,36817,TCP,281,Control,HTTP,Nihil praesentium asperiores omnis ullam liber...,...,NaN,NaN,Firewall,Opera,8,Linux,None,<NA>,<NA>,PC
12,2020-09-30 21:35:31,57.91.207.84,98.96.110.38,53471,38048,ICMP,64,Control,DNS,Earum sit est et eaque ipsam. Vero repellendus...,...,Log Data,Alert Data,Server,Opera,8,Windows,Vista,<NA>,<NA>,PC
13,2021-01-13 02:30:18,80.28.21.123,111.204.103.106,43729,10845,ICMP,1341,Data,HTTP,Ab voluptatibus nam aperiam. Est sed nostrum a...,...,NaN,NaN,Firewall,IE,7,Windows,10,<NA>,<NA>,PC
14,2023-02-01 13:17:17,54.163.130.178,62.112.149.214,47795,35243,UDP,913,Data,DNS,Sit doloremque explicabo. Cupiditate placeat e...,...,NaN,NaN,Firewall,Firefox,3,Linux,None,<NA>,<NA>,PC
15,2023-09-15 20:35:21,130.163.192.252,12.192.2.112,24912,21176,TCP,425,Data,DNS,Voluptates nam doloremque. Eius amet officiis ...,...,Log Data,NaN,Firewall,Opera,8,Linux,None,<NA>,<NA>,PC
16,2023-04-18 16:46:46,4.255.187.165,136.159.186.239,39934,5259,TCP,838,Control,HTTP,Sed facere culpa aliquam. Adipisci error quisq...,...,Log Data,NaN,Server,Opera,8,Windows,7,<NA>,<NA>,PC
17,2023-02-21 07:02:55,212.164.196.41,32.26.31.49,16513,50583,TCP,969,Data,HTTP,Dolore nisi voluptatem. Debitis explicabo fuga...,...,Log Data,Alert Data,Firewall,Chrome,46,Linux,None,<NA>,<NA>,PC
18,2020-12-29 02:50:47,119.101.120.119,47.125.34.52,4510,26783,TCP,124,Control,DNS,Qui sapiente laboriosam minima veritatis imped...,...,NaN,NaN,Firewall,IE,8,Windows,10,<NA>,<NA>,PC
19,2020-07-27 00:00:53,104.176.150.78,110.80.185.102,55147,17595,TCP,461,Data,HTTP,Ipsa est placeat cumque ut id. Quisquam provid...,...,Log Data,Alert Data,Server,Firefox iOS,18,iOS,12,iPhone,Apple,Mobile
20,2021-07-16 20:45:42,116.61.253.182,170.92.148.90,24907,37634,ICMP,845,Control,DNS,Ipsam ullam doloribus magni eos beatae eveniet...,...,Log Data,NaN,Firewall,Safari,4,Mac OS X,10,Mac,Apple,PC
21,2022-04-29 14:46:46,214.247.90.42,196.26.121.164,37998,1757,UDP,410,Control,DNS,Architecto voluptatum delectus.\nAut quia fugi...,...,Log Data,Alert Data,Server,Safari,4,Windows,2000,<NA>,<NA>,PC
22,2023-02-24 06:39:25,57.7.171.107,76.146.23.52,3133,46077,UDP,1425,Data,DNS,Praesentium voluptatibus sapiente.,...,NaN,Alert Data,Server,IE,5,Windows,95,<NA>,<NA>,Unknown
23,2023-09-15 15:43:03,46.236.76.78,68.194.124.162,40832,28015,UDP,118,Data,HTTP,Esse porro corrupti. Iusto magnam sunt dolorem...,...,NaN,NaN,Firewall,IE,9,Windows,2000,<NA>,<NA>,PC
24,2023-10-06 06:53:51,71.41.31.239,105.193.254.47,39911,27107,TCP,1386,Control,DNS,Ducimus totam dolor fugiat ipsa. Eum quas cons...,...,Log Data,NaN,Server,IE,5,Windows,XP,<NA>,<NA>,PC
25,2023-10-06 02:37:35,128.47.86.24,9.149.23.14,23021,31279,UDP,433,Control,DNS,Neque repellendus modi debitis dolorem officia...,...,Log Data,Alert Data,Firewall,Safari,5,Windows,ME,<NA>,<NA>,PC
26,2021-01-31 03:12:04,182.232.245.98,153.211.183.215,32552,15521,UDP,531,Control,FTP,Ad officia corporis laudantium enim cumque fac...,...,Log Data,Alert Data,Firewall,Safari,5,Windows,XP,<NA>,<NA>,PC
27,2020-08-28 09:54:45,208.44.127.159,121.167.40.167,56607,33023,TCP,282,Control,HTTP,Fugit quae placeat dicta tenetur ipsa. Facilis...,...,NaN,Alert Data,Firewall,IE,9,Windows,Vista,<NA>,<NA>,PC
28,2021-05-29 15:33:51,197.137.61.248,87.49.219.65,64351,43307,ICMP,1487,Control,HTTP,Esse esse optio excepturi delectus dolore mole...,...,Log Data,Alert Data,Firewall,Opera,8,Linux,None,<NA>,<NA>,PC
29,2022-05-30 18:26:12,69.60.34.24,160.208.108.125,19954,11594,UDP,563,Control,DNS,Quasi tempore quam recusandae. Voluptate earum...,...,Log Data,Alert Data,Firewall,Chrome,61,Linux,None,<NA>,<NA>,PC

In [143]:
df['is_bot'] = df['Device Information'].apply(lambda x: ua_parse(x).is_bot)
ua_parse("Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)").is_bot

True

In [144]:
df.head(30)

,Timestamp,Source IP Address,Destination IP Address,Source Port,Destination Port,Protocol,Packet Length,Packet Type,Traffic Type,Payload Data,...,IDS/IPS Alerts,Log Source,Browser_family,Browser_major,OS_family,OS_major,Device_family,Device_brand,Device_type,is_bot
0,2023-05-30 06:33:58,103.216.15.12,84.9.164.252,31225,17616,ICMP,503,Data,HTTP,Qui natus odio asperiores nam. Optio nobis ius...,...,NaN,Server,IE,9,Windows,8,<NA>,<NA>,PC,False
1,2020-08-26 07:08:30,78.199.217.198,66.191.137.154,17245,48166,ICMP,1174,Data,HTTP,Aperiam quos modi officiis veritatis rem. Omni...,...,NaN,Firewall,IE,8,Windows,Vista,<NA>,<NA>,PC,False
2,2022-11-13 08:23:25,63.79.210.48,198.219.82.17,16811,53600,UDP,306,Control,HTTP,Perferendis sapiente vitae soluta. Hic delectu...,...,Alert Data,Firewall,IE,9,Windows,8,<NA>,<NA>,PC,False
3,2023-07-02 10:38:46,163.42.196.10,101.228.192.255,20018,32534,UDP,385,Data,HTTP,Totam maxime beatae expedita explicabo porro l...,...,Alert Data,Firewall,Firefox,11,Mac OS X,10,Mac,Apple,PC,False
4,2023-07-16 13:11:07,71.166.185.76,189.243.174.238,6131,26646,TCP,1462,Data,DNS,Odit nesciunt dolorem nisi iste iusto. Animi v...,...,Alert Data,Firewall,IE,5,Windows,8,<NA>,<NA>,PC,False
5,2022-10-28 13:14:27,198.102.5.160,147.190.155.133,17430,52805,UDP,1423,Data,HTTP,Repellat quas illum harum fugit incidunt exerc...,...,NaN,Server,Opera,8,Linux,None,<NA>,<NA>,PC,False
6,2022-05-16 17:55:43,97.253.103.59,77.16.101.53,26562,17416,TCP,379,Data,DNS,Qui numquam inventore repellat ratione fugit o...,...,NaN,Server,Opera,9,Linux,None,<NA>,<NA>,PC,False
7,2023-02-12 07:13:17,11.48.99.245,178.157.14.116,34489,20396,ICMP,1022,Data,DNS,Amet libero optio quidem praesentium libero. E...,...,Alert Data,Firewall,Chrome,45,Mac OS X,10,Mac,Apple,PC,False
8,2023-06-27 11:02:56,49.32.208.167,72.202.237.9,56296,20857,TCP,1281,Control,FTP,Veritatis nihil amet atque molestias aperiam m...,...,Alert Data,Server,Chrome,38,Mac OS X,10,Mac,Apple,PC,False
9,2021-08-15 22:29:04,114.109.149.113,160.88.194.172,37918,50039,UDP,224,Data,HTTP,Consequatur ipsum autem reprehenderit quae. Do...,...,NaN,Server,Safari,4,Windows,Vista,<NA>,<NA>,PC,False
10,2022-07-20 13:28:50,177.21.83.200,196.218.124.169,35538,35006,ICMP,661,Data,HTTP,Sequi maxime voluptate ea. Eius officiis eaque...,...,NaN,Server,Mobile Safari,4,iOS,4,iPod,Apple,Mobile,False
11,2022-06-26 15:15:50,92.4.25.171,112.43.185.24,10903,36817,TCP,281,Control,HTTP,Nihil praesentium asperiores omnis ullam liber...,...,NaN,Firewall,Opera,8,Linux,None,<NA>,<NA>,PC,False
12,2020-09-30 21:35:31,57.91.207.84,98.96.110.38,53471,38048,ICMP,64,Control,DNS,Earum sit est et eaque ipsam. Vero repellendus...,...,Alert Data,Server,Opera,8,Windows,Vista,<NA>,<NA>,PC,False
13,2021-01-13 02:30:18,80.28.21.123,111.204.103.106,43729,10845,ICMP,1341,Data,HTTP,Ab voluptatibus nam aperiam. Est sed nostrum a...,...,NaN,Firewall,IE,7,Windows,10,<NA>,<NA>,PC,False
14,2023-02-01 13:17:17,54.163.130.178,62.112.149.214,47795,35243,UDP,913,Data,DNS,Sit doloremque explicabo. Cupiditate placeat e...,...,NaN,Firewall,Firefox,3,Linux,None,<NA>,<NA>,PC,False
15,2023-09-15 20:35:21,130.163.192.252,12.192.2.112,24912,21176,TCP,425,Data,DNS,Voluptates nam doloremque. Eius amet officiis ...,...,NaN,Firewall,Opera,8,Linux,None,<NA>,<NA>,PC,False
16,2023-04-18 16:46:46,4.255.187.165,136.159.186.239,39934,5259,TCP,838,Control,HTTP,Sed facere culpa aliquam. Adipisci error quisq...,...,NaN,Server,Opera,8,Windows,7,<NA>,<NA>,PC,False
17,2023-02-21 07:02:55,212.164.196.41,32.26.31.49,16513,50583,TCP,969,Data,HTTP,Dolore nisi voluptatem. Debitis explicabo fuga...,...,Alert Data,Firewall,Chrome,46,Linux,None,<NA>,<NA>,PC,False
18,2020-12-29 02:50:47,119.101.120.119,47.125.34.52,4510,26783,TCP,124,Control,DNS,Qui sapiente laboriosam minima veritatis imped...,...,NaN,Firewall,IE,8,Windows,10,<NA>,<NA>,PC,False
19,2020-07-27 00:00:53,104.176.150.78,110.80.185.102,55147,17595,TCP,461,Data,HTTP,Ipsa est placeat cumque ut id. Quisquam provid...,...,Alert Data,Server,Firefox iOS,18,iOS,12,iPhone,Apple,Mobile,False
20,2021-07-16 20:45:42,116.61.253.182,170.92.148.90,24907,37634,ICMP,845,Control,DNS,Ipsam ullam doloribus magni eos beatae eveniet...,...,NaN,Firewall,Safari,4,Mac OS X,10,Mac,Apple,PC,False
21,2022-04-29 14:46:46,214.247.90.42,196.26.121.164,37998,1757,UDP,410,Control,DNS,Architecto voluptatum delectus.\nAut quia fugi...,...,Alert Data,Server,Safari,4,Windows,2000,<NA>,<NA>,PC,False
22,2023-02-24 06:39:25,57.7.171.107,76.146.23.52,3133,46077,UDP,1425,Data,DNS,Praesentium voluptatibus sapiente.,...,Alert Data,Server,IE,5,Windows,95,<NA>,<NA>,Unknown,False
23,2023-09-15 15:43:03,46.236.76.78,68.194.124.162,40832,28015,UDP,118,Data,HTTP,Esse porro corrupti. Iusto magnam sunt dolorem...,...,NaN,Firewall,IE,9,Windows,2000,<NA>,<NA>,PC,False
24,2023-10-06 06:53:51,71.41.31.239,105.193.254.47,39911,27107,TCP,1386,Control,DNS,Ducimus totam dolor fugiat ipsa. Eum quas cons...,...,NaN,Server,IE,5,Windows,XP,<NA>,<NA>,PC,False
25,2023-10-06 02:37:35,128.47.86.24,9.149.23.14,23021,31279,UDP,433,Control,DNS,Neque repellendus modi debitis dolorem officia...,...,Alert Data,Firewall,Safari,5,Windows,ME,<NA>,<NA>,PC,False
26,2021-01-31 03:12:04,182.232.245.98,153.211.183.215,32552,15521,UDP,531,Control,FTP,Ad officia corporis laudantium enim cumque fac...,...,Alert Data,Firewall,Safari,5,Windows,XP,<NA>,<NA>,PC,False
27,2020-08-28 09:54:45,208.44.127.159,121.167.40.167,56607,33023,TCP,282,Control,HTTP,Fugit quae placeat dicta tenetur ipsa. Facilis...,...,Alert Data,Firewall,IE,9,Windows,Vista,<NA>,<NA>,PC,False
28,2021-05-29 15:33:51,197.137.61.248,87.49.219.65,64351,43307,ICMP,1487,Control,HTTP,Esse esse optio excepturi delectus dolore mole...,...,Alert Data,Firewall,Opera,8,Linux,None,<NA>,<NA>,PC,False
29,2022-05-30 18:26:12,69.60.34.24,160.208.108.125,19954,11594,UDP,563,Control,DNS,Quasi tempore quam recusandae. Voluptate earum...,...,Alert Data,Firewall,Chrome,61,Linux,None,<NA>,<NA>,PC,False

In [145]:
df

,Timestamp,Source IP Address,Destination IP Address,Source Port,Destination Port,Protocol,Packet Length,Packet Type,Traffic Type,Payload Data,...,IDS/IPS Alerts,Log Source,Browser_family,Browser_major,OS_family,OS_major,Device_family,Device_brand,Device_type,is_bot
0,2023-05-30 06:33:58,103.216.15.12,84.9.164.252,31225,17616,ICMP,503,Data,HTTP,Qui natus odio asperiores nam. Optio nobis ius...,...,NaN,Server,IE,9,Windows,8,<NA>,<NA>,PC,False
1,2020-08-26 07:08:30,78.199.217.198,66.191.137.154,17245,48166,ICMP,1174,Data,HTTP,Aperiam quos modi officiis veritatis rem. Omni...,...,NaN,Firewall,IE,8,Windows,Vista,<NA>,<NA>,PC,False
2,2022-11-13 08:23:25,63.79.210.48,198.219.82.17,16811,53600,UDP,306,Control,HTTP,Perferendis sapiente vitae soluta. Hic delectu...,...,Alert Data,Firewall,IE,9,Windows,8,<NA>,<NA>,PC,False
3,2023-07-02 10:38:46,163.42.196.10,101.228.192.255,20018,32534,UDP,385,Data,HTTP,Totam maxime beatae expedita explicabo porro l...,...,Alert Data,Firewall,Firefox,11,Mac OS X,10,Mac,Apple,PC,False
4,2023-07-16 13:11:07,71.166.185.76,189.243.174.238,6131,26646,TCP,1462,Data,DNS,Odit nesciunt dolorem nisi iste iusto. Animi v...,...,Alert Data,Firewall,IE,5,Windows,8,<NA>,<NA>,PC,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39995,2023-05-26 14:08:42,26.36.109.26,121.100.75.240,31005,6764,UDP,1428,Control,HTTP,Quibusdam ullam consequatur consequuntur accus...,...,Alert Data,Firewall,Firefox iOS,17,iOS,14,iPad,Apple,Tablet,False
39996,2023-03-27 00:38:27,17.21.163.81,196.108.134.78,2553,28091,UDP,1184,Control,HTTP,Quaerat neque esse. Animi expedita natus commo...,...,NaN,Firewall,Safari,4,Windows,ME,<NA>,<NA>,PC,False
39997,2022-03-31 01:45:49,162.35.217.57,98.107.0.15,22505,25152,UDP,1043,Data,DNS,Enim at aspernatur illum. Saepe numquam eligen...,...,Alert Data,Server,Safari,4,Windows,NT,<NA>,<NA>,PC,False
39998,2023-09-22 18:32:38,208.72.233.205,173.79.112.252,20013,2703,UDP,483,Data,FTP,Officiis dolorem sed harum provident earum dis...,...,NaN,Server,Chrome,15,Linux,None,<NA>,<NA>,PC,False
39999,2023-10-10 11:59:52,14.102.21.108,109.198.45.7,50137,55575,ICMP,1175,Control,HTTP,Eligendi omnis voluptate nihil voluptatibus do...,...,Alert Data,Firewall,Mobile Safari,4,iOS,3,iPod,Apple,Mobile,False

In [79]:
df.head(10)

,Timestamp,Source IP Address,Destination IP Address,Source Port,Destination Port,Protocol,Packet Length,Packet Type,Traffic Type,Payload Data,...,Proxy Information,Firewall Logs,IDS/IPS Alerts,Log Source,Browser_family,Browser_major,OS_family,OS_major,Device_family,Device_brand
0,2023-05-30 06:33:58,103.216.15.12,84.9.164.252,31225,17616,ICMP,503,Data,HTTP,Qui natus odio asperiores nam. Optio nobis ius...,...,150.9.97.135,Log Data,NaN,Server,IE,9,Windows,8,<NA>,<NA>
1,2020-08-26 07:08:30,78.199.217.198,66.191.137.154,17245,48166,ICMP,1174,Data,HTTP,Aperiam quos modi officiis veritatis rem. Omni...,...,NaN,Log Data,NaN,Firewall,IE,8,Windows,Vista,<NA>,<NA>
2,2022-11-13 08:23:25,63.79.210.48,198.219.82.17,16811,53600,UDP,306,Control,HTTP,Perferendis sapiente vitae soluta. Hic delectu...,...,114.133.48.179,Log Data,Alert Data,Firewall,IE,9,Windows,8,<NA>,<NA>
3,2023-07-02 10:38:46,163.42.196.10,101.228.192.255,20018,32534,UDP,385,Data,HTTP,Totam maxime beatae expedita explicabo porro l...,...,NaN,NaN,Alert Data,Firewall,Firefox,11,Mac OS X,10,Mac,Apple
4,2023-07-16 13:11:07,71.166.185.76,189.243.174.238,6131,26646,TCP,1462,Data,DNS,Odit nesciunt dolorem nisi iste iusto. Animi v...,...,149.6.110.119,NaN,Alert Data,Firewall,IE,5,Windows,8,<NA>,<NA>
5,2022-10-28 13:14:27,198.102.5.160,147.190.155.133,17430,52805,UDP,1423,Data,HTTP,Repellat quas illum harum fugit incidunt exerc...,...,NaN,NaN,NaN,Server,Opera,8,Linux,None,<NA>,<NA>
6,2022-05-16 17:55:43,97.253.103.59,77.16.101.53,26562,17416,TCP,379,Data,DNS,Qui numquam inventore repellat ratione fugit o...,...,NaN,Log Data,NaN,Server,Opera,9,Linux,None,<NA>,<NA>
7,2023-02-12 07:13:17,11.48.99.245,178.157.14.116,34489,20396,ICMP,1022,Data,DNS,Amet libero optio quidem praesentium libero. E...,...,192.31.159.5,Log Data,Alert Data,Firewall,Chrome,45,Mac OS X,10,Mac,Apple
8,2023-06-27 11:02:56,49.32.208.167,72.202.237.9,56296,20857,TCP,1281,Control,FTP,Veritatis nihil amet atque molestias aperiam m...,...,NaN,Log Data,Alert Data,Server,Chrome,38,Mac OS X,10,Mac,Apple
9,2021-08-15 22:29:04,114.109.149.113,160.88.194.172,37918,50039,UDP,224,Data,HTTP,Consequatur ipsum autem reprehenderit quae. Do...,...,87.128.245.244,NaN,NaN,Server,Safari,4,Windows,Vista,<NA>,<NA>

In [ ]:
ua_strings = [
"Mozilla/5.0 (iPhone; CPU iPhone OS 5_1_1 like Mac OS X) AppleWebKit/533.0 (KHTML, like Gecko) CriOS/51.0.844.0 Mobile/22B509 Safari/533.0",
"Opera/8.11.(Windows 98; Win 9x 4.90; da-DK) Presto/2.9.177 Version/10.00",
"Mozilla/5.0 (Android 7.1; Mobile; rv:22.0) Gecko/22.0 Firefox/22.0",
"Mozilla/5.0 (Windows; U; Windows NT 6.0) AppleWebKit/533.28.5 (KHTML, like Gecko) Version/4.0 Safari/533.28.5",
"Mozilla/5.0 (iPhone; CPU iPhone OS 12_4_8 like Mac OS X) AppleWebKit/533.2 (KHTML, like Gecko) FxiOS/18.1i4735.0 Mobile/92M384 Safari/533.2",
"Mozilla/5.0 (compatible; MSIE 5.0; Windows 95; Trident/5.1)",
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/532.1 (KHTML, like Gecko) Chrome/32.0.844.0 Safari/532.1"
]

parsed = [parse(s) for s in ua_strings]
parsed

In [ ]:
# Test code if object value is None, to avoid error of filling attributes 
parsedURL = parse("Mozilla/5.0 (compatible; MSIE 8.0; Windows NT 6.2; Trident/5.0")
parsedURL2 = parse("Mozilla/5.0 (Macintosh; PPC Mac OS X 10_11_5; rv:1.9.6.20) Gecko/2583-02-14 13:30:10 Firefox/11.0")
if parsedURL2.__getattribute__('device') is not pd.NA:
    test = parsedURL2.__getattribute__('device').family
test

In [ ]:
# Test with one row before applying to df
test = parse(df.loc[0, "Device Information"])
browser_family = test.__getattribute__('user_agent').family
browser_family

In [ ]:
df.head(5)

In [ ]:
df.isna().sum()

In [ ]:
# display non-numeric columns for team distribution tasks (working on categorical features)
df.select_dtypes(exclude=[np.number]).columns.tolist()

In [ ]:
# ASK: only 1 destionation IP appears in source IPs, what does this mean? cause both looks inbound traffic.
# find destination IPs that appear in Source IPs without modifying df
destIPinSourceIP = df['Destination IP Address'].isin(df['Source IP Address'])
matched_rows = df[destIPinSourceIP].copy()  # recuperate whole rows
matched_rows

# df.drop(columns=['Dest_in_Source'])

In [ ]:
# take the first three octets of the IP as a list
split = "103.216.15.12".split(".")[:3]
ip3 = ".".join(split)
ip3

In [ ]:
# Split all IPs to /24 subnet ==> local subnet/Single host
def splitIP24(ip):
    if pd.isna(ip):
        return pd.NA
    return ".".join(ip.split(".")[:3])

# Split all IPs to /16 subnet ==> network owner/region (ISP/backbone provider)
def splitIP16(ip):
    if pd.isna(ip):
        return pd.NA
    return ".".join(ip.split(".")[:2])

df['Source IP Address_24'] = df['Source IP Address'].apply(splitIP24)
df['Source IP Address_16'] = df['Source IP Address'].apply(splitIP16)

df['Destination IP Address_24'] = df['Destination IP Address'].apply(splitIP24)
df['Destination IP Address_16'] = df['Destination IP Address'].apply(splitIP16)

df['Proxy Information_24'] = df['Proxy Information'].apply(splitIP24)
df['Proxy Information_16'] = df['Proxy Information'].apply(splitIP16)

df.head(2)

In [ ]:
# Check private range
# • 10.0.0.0 – 10.255.255.255 
# • 172.16.0.0 – 172.31.255.255 
# • 192.168.0.0 – 192.168.255.255

def isPrivateIP(ip):
    if pd.isna(ip):
        return pd.NA
    octets = ip.split(".")
    first = int(octets[0])
    second = int(octets[1])
    if first == 10:
        return True
    elif first == 172 and 16 <= second <= 31:
        return True
    elif first == 192 and second == 168:
        return True
    else:
        return False

df['Source_IP_Private'] = df['Source IP Address'].apply(isPrivateIP)
df['Destination_IP_Private'] = df['Destination IP Address'].apply(isPrivateIP)
df['Proxy_IP_Private'] = df['Proxy Information'].apply(isPrivateIP)

df.head(10)

In [ ]:
df

In [ ]:
with geoip2.database.Reader('./data/ext/GeoLite2-Country_20251212/GeoLite2-Country.mmdb') as reader:
    response = reader.country(df.loc[0, 'Source IP Address'])
    print(response)
    # print(response.continent.names)

In [ ]:
df_test = df.head(2)
df_test

In [ ]:
import geoip2.errors
with geoip2.database.Reader('./data/ext/GeoLite2-Country_20251212/GeoLite2-Country.mmdb') as reader:
    def _lookup_ip(ip):
        # 1. Handle missing/NA values
        if not ip or pd.isna(ip):
            return {
                'ContinentName': pd.NA,
                'CountryName': pd.NA,
            }
        
        # 2. Perform external lookup
        try:
            response = reader.country(ip)
            
            # 3. RETURN A DICTIONARY of all desired features
            return {
                'ContinentName': response.continent.name,
                'CountryName': response.country.name,
            }
        
        except geoip2.errors.AddressNotFoundError:
            # 4. Return NA dictionary for not found IPs
            return {
                'ContinentName': pd.NA,
                'CountryName': pd.NA,
                # 'ASN': pd.NA,
                # 'Is_Private': False
            }
        except Exception:
            # 5. Return NA dictionary for other errors
            return {
                'ContinentNamee': pd.NA,
                'CountryName': pd.NA,
                # 'ASN': pd.NA,
                # 'Is_Private': False
            }

    # --- Applying the Function ---
    geo_results_sourceIP = df['Source IP Address'].apply(_lookup_ip)
    geo_results_destIP = df['Destination IP Address'].apply(_lookup_ip)
    geo_results_proxyIP = df['Proxy Information'].apply(_lookup_ip)

    # print('geo_results_sourceIP', geo_results_sourceIP)
    # Convert list of dictionaries to DataFrame
    geo_df_sourceIP = pd.DataFrame(geo_results_sourceIP.tolist(), index=geo_results_sourceIP.index)
    # print('geo_df_sourceIP', geo_df_sourceIP)
    geo_df_destIP = pd.DataFrame(geo_results_destIP.tolist(), index=geo_results_destIP.index)
    print('geo_df_destIP', geo_df_destIP)

    geo_df_proxyIP = pd.DataFrame(geo_results_proxyIP.tolist(), index=geo_results_proxyIP.index)

    # test to df_test before real df
    # df_test.loc[:, ('ContinentName_Source', 'CountryName_Source')] = geo_df_sourceIP[['ContinentName', 'CountryName']]
    # Source IP
    df['ContinentName_Source'] = geo_df_sourceIP['ContinentName']
    df['CountryName_Source'] = geo_df_sourceIP['CountryName']
    # df.loc[:, ('ContinentName_Source', 'CountryName_Source')] = geo_df_sourceIP[['ContinentName', 'CountryName']]
    # print('am here')
    
    # Destination IP
    df['ContinentName_Destination'] = geo_df_destIP['ContinentName']
    df['CountryName_Destination'] = geo_df_destIP['CountryName']

    # Proxy IP
    df['ContinentName_Proxy'] = geo_df_proxyIP['ContinentName']
    df['CountryName_Proxy'] = geo_df_proxyIP['CountryName']

In [ ]:
# test to df_test before real df
# df_test
df.head(5)

In [ ]:
with geoip2.database.Reader('./data/ext/GeoLite2-City_20251212/GeoLite2-City.mmdb') as reader:
    response = reader.city(df.loc[0, 'Source IP Address'])
    print(response)
    print(response.city.name)
    print(response.location.latitude)
    print(response.location.longitude)
    # print(response.postal.code)

In [ ]:
import geoip2.errors
with geoip2.database.Reader('./data/ext/GeoLite2-City_20251212/GeoLite2-City.mmdb') as reader:
    def _lookup_ip(ip):
        # 1. Handle missing/NA values
        if not ip or pd.isna(ip):
            return {
                'CityName': pd.NA,
                'CityLat_Source': pd.NA,
                'CityLon': pd.NA,
            }
        
        # 2. Perform external lookup
        try:
            response = reader.city(ip)
            
            # 3. RETURN A DICTIONARY of all desired features
            return {
                    'CityName': response.city.name,
                    'CityLat': response.location.latitude,
                    'CityLon': response.location.longitude,
            }
        
        except geoip2.errors.AddressNotFoundError:
            # 4. Return NA dictionary for not found IPs
            return {
                'CityName': pd.NA,
                'CityLat': pd.NA,
                'CityLon': pd.NA,
                # 'ASN': pd.NA,
                # 'Is_Private': False
            }
        except Exception:
            # 5. Return NA dictionary for other errors
            return {
                'CityName': pd.NA,
                'CityLat': pd.NA,
                'CityLon': pd.NA,
                # 'ASN': pd.NA,
                # 'Is_Private': False
            }

    # --- Applying the Function ---
    geo_results_sourceIP = df['Source IP Address'].apply(_lookup_ip)
    geo_results_destIP = df['Destination IP Address'].apply(_lookup_ip)
    geo_results_proxyIP = df['Proxy Information'].apply(_lookup_ip)

    # print(geo_results_sourceIP)
    # Convert list of dictionaries to DataFrame
    geo_df_sourceIP = pd.DataFrame(geo_results_sourceIP.tolist(), index=geo_results_sourceIP.index)
    geo_df_destIP = pd.DataFrame(geo_results_destIP.tolist(), index=geo_results_destIP.index)
    geo_df_proxyIP = pd.DataFrame(geo_results_proxyIP.tolist(), index=geo_results_proxyIP.index)
    # print(geo_df_sourceIP)

    # test to df_test before real df
    # df_test.loc[:, ('CityName_Source', 'CityLat_Source', 'CityLon_Source')] = geo_df[['CityName_Source', 'CityLat_Source', 'CityLon_Source']]
    df['CityName_Proxy'] = geo_df_proxyIP['CityName']
    df['CityLat_Proxy'] = geo_df_proxyIP['CityLat']
    df['CityLon_Proxy'] = geo_df_proxyIP['CityLon']

    df['CityName_Destination'] = geo_df_destIP['CityName']
    df['CityLat_Destination'] = geo_df_destIP['CityLat']
    df['CityLon_Destination'] = geo_df_destIP['CityLon']

    df['CityName_Source'] = geo_df_sourceIP['CityName']
    df['CityLat_Source'] = geo_df_sourceIP['CityLat']
    df['CityLon_Source'] = geo_df_sourceIP['CityLon']

    # why codes below didnt work??
    # df.loc[:, ('CityName_Source', 'CityLat_Source', 'CityLon_Source')] = geo_df_sourceIP[['CityName', 'CityLat', 'CityLon']]
    # df.loc[:, ('CityName_Destination', 'CityLat_Destination', 'CityLon_Destination')] = geo_df_destIP[['CityName', 'CityLat', 'CityLon']]
    # df.loc[:, ('CityName_Proxy', 'CityLat_Proxy', 'CityLon_Proxy')] = geo_df_proxyIP[['CityName', 'CityLat', 'CityLon']]

In [ ]:
# test to df_test before real df
# df_test
df.head(5)

In [ ]:
df

In [ ]:
# Treat ASN for IP source?

In [ ]:
# Treat ports
# HTTPS 443, SSH 22, DNS 53, FTP 20-21) 
# Well-known (0–1023) → common services (HTTP, FTP, DNS, etc.) 
# User/Registered Ports (1024-49151) → used by Server, Application, Database, VPN (HTTP alternate 8080, MySQL 3306) 
# Dynamic and/or Private Ports (49152-65535) → temporary/ephemeral ports for outgoing connections, used by Clients. Rapid rotation may signal botnets. 
# Plot to see distribution of these different ports vs packet length 
# Also vs protocol/traffic type/attack type, etc ? Any meaning? 
def portCategory(port):
    if pd.isna(port):
        return pd.NA
    elif 0 <= port <= 1023:
        return 'Well-known'
    elif 1024 <= port <= 49151:
        return 'User/Registered'
    elif 49152 <= port <= 65535:
        return 'Dynamic/Private'
    else:
        return 'Invalid'

df['Source Port_Cat'] = df['Source Port'].apply(portCategory)
df['Destination Port_Cat'] = df['Destination Port'].apply(portCategory)

In [ ]:
df.head(5)

In [ ]:
df

In [ ]:
# How to treat timestamps?
# Timeseries?

In [ ]:
# Plot Browser_family vs Attack Type (stacked bar for top N browser families)
# create a contingency table: rows = Browser_family, columns = Attack Type
ct = pd.crosstab(df['Browser_family'], df['Attack Type'])

# show full table (or limit to top N browser families by total count)
# top_n = 10
top_browsers = ct.sum(axis=1).sort_values(ascending=False).head(top_n).index
ct_top = ct.loc[top_browsers]

# display table
ct_top

# stacked bar plot for the top N browser families
ct_top.plot(kind='bar', stacked=True, figsize=(12,6))
plt.xlabel('Browser family')
plt.ylabel('Count')
plt.title(f'Browser family vs Attack Type (top {top_n} browser families)')
plt.legend(title='Attack Type', bbox_to_anchor=(1.02, 1), loc='upper left')
plt.tight_layout()
plt.show()

In [ ]:
# Plot OS_family vs Attack Type (stacked bar for top N browser families)
# create a contingency table: rows = Browser_family, columns = Attack Type
ct = pd.crosstab(df['OS_family'], df['Attack Type'])

# show full table (or limit to top N browser families by total count)
top_n = 10
top_browsers = ct.sum(axis=1).sort_values(ascending=False).head(top_n).index
ct_top = ct.loc[top_browsers]

# display table
ct_top

# stacked bar plot for the top N browser families
ct_top.plot(kind='bar', stacked=True, figsize=(12,6))
plt.xlabel('OS family')
plt.ylabel('Count')
plt.title(f'OS family vs Attack Type (top {top_n} OS families)')
plt.legend(title='Attack Type', bbox_to_anchor=(1.02, 1), loc='upper left')
plt.tight_layout()
plt.show()

In [ ]:
# Plot Source Port_Cat vs Attack Type (stacked bar for top N browser families)
# create a contingency table: rows = Browser_family, columns = Attack Type
ct = pd.crosstab(df['Source Port_Cat'], df['Attack Type'])

# show full table (or limit to top N browser families by total count)
# top_n = 10
top_browsers = ct.sum(axis=1).sort_values(ascending=False).head(top_n).index
ct_top = ct.loc[top_browsers]

# display table
ct_top

# stacked bar plot for the top N browser families
ct_top.plot(kind='bar', stacked=True, figsize=(12,6))
plt.xlabel('Source Port_Cat')
plt.ylabel('Count')
plt.title(f'Source Port_Cat vs Attack Type (top {top_n} Source Port_Cat)')
plt.legend(title='Attack Type', bbox_to_anchor=(1.02, 1), loc='upper left')
plt.tight_layout()
plt.show()

In [ ]:
df.corr(numeric_only=True)

In [ ]:
cols_to_check = [
    "Attack Signature",
    "Severity Level",
    "Action Taken",
    "IDS/IPS Alerts",
    "Malware Indicators",
    "Alerts/Warnings",
    "Network Segment",
    "Firewall Logs",
    "Log Source"
]
for col in cols_to_check:
    print(f"\n--- {col} ---")
    print(df.groupby('Attack Type')[col].value_counts(dropna=False))

In [ ]:
# is it good news cause our model won't have bias for this colums cause it has pretty  fair distribution? or there is other meaning?
df.groupby('Attack Type')['Firewall Logs'].value_counts()

In [ ]:
df.groupby('Attack Type')['Firewall Logs'].value_counts(dropna=False)

In [ ]:
# is it good news cause our model won't have bias for this colums cause it has pretty  fair distribution? or there is other meaning?
df.groupby('Attack Type')['Alerts/Warnings'].value_counts()

In [ ]:
df.groupby('Attack Type')['Alerts/Warnings'].value_counts(dropna=False)

In [ ]:
# is it good news cause our model won't have bias for this colums cause it has pretty  fair distribution? or there is other meaning?
df.groupby('Attack Type')['Malware Indicators'].value_counts()

In [ ]:
df.groupby('Attack Type')['Malware Indicators'].value_counts(dropna=False)

In [ ]:
df.groupby('Attack Type')['IDS/IPS Alerts'].value_counts()

In [ ]:
df.groupby('Attack Type')['IDS/IPS Alerts'].value_counts(dropna=False)

In [ ]:
sns.histplot(x="Malware Indicators",hue="Attack Type",multiple="stack", data=df)
plt.show()

In [ ]:
df.groupby('Attack Type')['Firewall Logs'].value_counts()

In [ ]:
# entropy doesn't make any sense as the payload data seems like synthetic (need to check with Hanna).
from collections import Counter

def entropy_bytes(s):
    b = str(s).encode('utf-8', errors='ignore')
    if not b: return 0.0
    counts = Counter(b)
    total = len(b)
    return -sum((c/total) * math.log2(c/total) for c in counts.values())

df['Entropy'] = df['Payload Data'].apply(entropy_bytes)
df['Band'] = df['Entropy'].apply(lambda e: 'High' if e > 7 else ('Medium' if e >= 5 else 'Low'))
print(df['Band'].value_counts())

In [ ]:
df.groupby('Attack Type')['Packet Length'].describe()

In [ ]:
# doesn't show spike of Blocked if Severity Level is High
df.groupby(['Attack Type', 'Severity Level'])['Action Taken'].value_counts()

In [ ]:
# Doesn't show that IDS/IPS Alert trigger Alerts/Warnings
df.groupby('IDS/IPS Alerts')['Alerts/Warnings'].value_counts(dropna=False)

In [ ]:
# Doesn't show that certain signature is assigned to attack type
df.groupby('Attack Type')['Attack Signature'].value_counts(dropna=False)