In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly as plty
import math
from ua_parser import parse
import geoip2.database

In [2]:

df = pd.read_csv("./data/int/cybersecurity_attacks.csv")

In [3]:
df

,Timestamp,Source IP Address,Destination IP Address,Source Port,Destination Port,Protocol,Packet Length,Packet Type,Traffic Type,Payload Data,...,Action Taken,Severity Level,User Information,Device Information,Network Segment,Geo-location Data,Proxy Information,Firewall Logs,IDS/IPS Alerts,Log Source
0,2023-05-30 06:33:58,103.216.15.12,84.9.164.252,31225,17616,ICMP,503,Data,HTTP,Qui natus odio asperiores nam. Optio nobis ius...,...,Logged,Low,Reyansh Dugal,Mozilla/5.0 (compatible; MSIE 8.0; Windows NT ...,Segment A,"Jamshedpur, Sikkim",150.9.97.135,Log Data,NaN,Server
1,2020-08-26 07:08:30,78.199.217.198,66.191.137.154,17245,48166,ICMP,1174,Data,HTTP,Aperiam quos modi officiis veritatis rem. Omni...,...,Blocked,Low,Sumer Rana,Mozilla/5.0 (compatible; MSIE 8.0; Windows NT ...,Segment B,"Bilaspur, Nagaland",NaN,Log Data,NaN,Firewall
2,2022-11-13 08:23:25,63.79.210.48,198.219.82.17,16811,53600,UDP,306,Control,HTTP,Perferendis sapiente vitae soluta. Hic delectu...,...,Ignored,Low,Himmat Karpe,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,Segment C,"Bokaro, Rajasthan",114.133.48.179,Log Data,Alert Data,Firewall
3,2023-07-02 10:38:46,163.42.196.10,101.228.192.255,20018,32534,UDP,385,Data,HTTP,Totam maxime beatae expedita explicabo porro l...,...,Blocked,Medium,Fateh Kibe,Mozilla/5.0 (Macintosh; PPC Mac OS X 10_11_5; ...,Segment B,"Jaunpur, Rajasthan",NaN,NaN,Alert Data,Firewall
4,2023-07-16 13:11:07,71.166.185.76,189.243.174.238,6131,26646,TCP,1462,Data,DNS,Odit nesciunt dolorem nisi iste iusto. Animi v...,...,Blocked,Low,Dhanush Chad,Mozilla/5.0 (compatible; MSIE 5.0; Windows NT ...,Segment C,"Anantapur, Tripura",149.6.110.119,NaN,Alert Data,Firewall
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39995,2023-05-26 14:08:42,26.36.109.26,121.100.75.240,31005,6764,UDP,1428,Control,HTTP,Quibusdam ullam consequatur consequuntur accus...,...,Logged,Medium,Adira Madan,Mozilla/5.0 (iPad; CPU iPad OS 14_2_1 like Mac...,Segment A,"Nashik, Manipur",NaN,Log Data,Alert Data,Firewall
39996,2023-03-27 00:38:27,17.21.163.81,196.108.134.78,2553,28091,UDP,1184,Control,HTTP,Quaerat neque esse. Animi expedita natus commo...,...,Logged,High,Rati Dara,Mozilla/5.0 (Windows; U; Windows 98; Win 9x 4....,Segment C,"Vadodara, Mizoram",60.51.30.46,Log Data,NaN,Firewall
39997,2022-03-31 01:45:49,162.35.217.57,98.107.0.15,22505,25152,UDP,1043,Data,DNS,Enim at aspernatur illum. Saepe numquam eligen...,...,Blocked,Low,Samiha Joshi,Mozilla/5.0 (Windows; U; Windows NT 4.0) Apple...,Segment C,"Mahbubnagar, Himachal Pradesh",NaN,Log Data,Alert Data,Server
39998,2023-09-22 18:32:38,208.72.233.205,173.79.112.252,20013,2703,UDP,483,Data,FTP,Officiis dolorem sed harum provident earum dis...,...,Ignored,Low,Rasha Chauhan,Mozilla/5.0 (X11; Linux i686) AppleWebKit/536....,Segment B,"Rourkela, Arunachal Pradesh",137.76.130.8,Log Data,NaN,Server
39999,2023-10-10 11:59:52,14.102.21.108,109.198.45.7,50137,55575,ICMP,1175,Control,HTTP,Eligendi omnis voluptate nihil voluptatibus do...,...,Logged,Medium,Zaina Kumar,Mozilla/5.0 (iPod; U; CPU iPhone OS 3_0 like M...,Segment A,"Pudukkottai, West Bengal",112.169.115.139,Log Data,Alert Data,Firewall

In [4]:
df.describe()

        Source Port  Destination Port  Packet Length  Anomaly Scores
count  40000.000000      40000.000000   40000.000000    40000.000000
mean   32970.356450      33150.868650     781.452725       50.113473
std    18560.425604      18574.668842     416.044192       28.853598
min     1027.000000       1024.000000      64.000000        0.000000
25%    16850.750000      17094.750000     420.000000       25.150000
50%    32856.000000      33004.500000     782.000000       50.345000
75%    48928.250000      49287.000000    1143.000000       75.030000
max    65530.000000      65535.000000    1500.000000      100.000000

In [5]:
df.shape

(40000, 25)

In [6]:
df.isna().sum()

Timestamp                     0
Source IP Address             0
Destination IP Address        0
Source Port                   0
Destination Port              0
Protocol                      0
Packet Length                 0
Packet Type                   0
Traffic Type                  0
Payload Data                  0
Malware Indicators        20000
Anomaly Scores                0
Alerts/Warnings           20067
Attack Type                   0
Attack Signature              0
Action Taken                  0
Severity Level                0
User Information              0
Device Information            0
Network Segment               0
Geo-location Data             0
Proxy Information         19851
Firewall Logs             19961
IDS/IPS Alerts            20050
Log Source                    0
dtype: int64

In [7]:
df.columns

Index(['Timestamp', 'Source IP Address', 'Destination IP Address',
       'Source Port', 'Destination Port', 'Protocol', 'Packet Length',
       'Packet Type', 'Traffic Type', 'Payload Data', 'Malware Indicators',
       'Anomaly Scores', 'Alerts/Warnings', 'Attack Type', 'Attack Signature',
       'Action Taken', 'Severity Level', 'User Information',
       'Device Information', 'Network Segment', 'Geo-location Data',
       'Proxy Information', 'Firewall Logs', 'IDS/IPS Alerts', 'Log Source'],
      dtype='object')

In [8]:
# Count Device Information that occured >= 30 times
df.value_counts("Device Information")[df.value_counts("Device Information") >= 30]

Device Information
Mozilla/5.0 (compatible; MSIE 6.0; Windows NT 6.2; Trident/3.0)     35
Mozilla/5.0 (compatible; MSIE 5.0; Windows 98; Trident/4.1)         34
Mozilla/5.0 (compatible; MSIE 6.0; Windows CE; Trident/4.0)         33
Mozilla/5.0 (compatible; MSIE 5.0; Windows NT 5.2; Trident/4.1)     31
Mozilla/5.0 (compatible; MSIE 7.0; Windows NT 6.0; Trident/3.0)     31
Mozilla/5.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0)     30
Mozilla/5.0 (compatible; MSIE 7.0; Windows 98; Trident/3.1)         30
Mozilla/5.0 (compatible; MSIE 8.0; Windows CE; Trident/3.0)         30
Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 10.0; Trident/4.0)    30
Mozilla/5.0 (compatible; MSIE 8.0; Windows NT 5.1; Trident/3.1)     30
Name: count, dtype: int64

In [9]:
# Test parse_os and create column with two values (if needed)
from ua_parser import parse_os
ua_string = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
parse_os(ua_string)
# os_family = parse_os(ua_string).__getattribute__('family')
os_family_major = f"{getattr(parse_os(ua_string), 'family')} {getattr(parse_os(ua_string), 'major')}"
os_family_major

'Windows 10'

In [10]:
ua_strings = [
"Mozilla/5.0 (iPhone; CPU iPhone OS 5_1_1 like Mac OS X) AppleWebKit/533.0 (KHTML, like Gecko) CriOS/51.0.844.0 Mobile/22B509 Safari/533.0",
"Opera/8.11.(Windows 98; Win 9x 4.90; da-DK) Presto/2.9.177 Version/10.00",
"Mozilla/5.0 (Android 7.1; Mobile; rv:22.0) Gecko/22.0 Firefox/22.0",
"Mozilla/5.0 (Windows; U; Windows NT 6.0) AppleWebKit/533.28.5 (KHTML, like Gecko) Version/4.0 Safari/533.28.5",
"Mozilla/5.0 (iPhone; CPU iPhone OS 12_4_8 like Mac OS X) AppleWebKit/533.2 (KHTML, like Gecko) FxiOS/18.1i4735.0 Mobile/92M384 Safari/533.2",
"Mozilla/5.0 (compatible; MSIE 5.0; Windows 95; Trident/5.1)",
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/532.1 (KHTML, like Gecko) Chrome/32.0.844.0 Safari/532.1"
]

parsed = [parse(s) for s in ua_strings]
parsed

[Result(user_agent=UserAgent(family='Chrome Mobile iOS', major='51', minor='0', patch='844', patch_minor='0'), os=OS(family='iOS', major='5', minor='1', patch='1', patch_minor=None), device=Device(family='iPhone', brand='Apple', model='iPhone'), string='Mozilla/5.0 (iPhone; CPU iPhone OS 5_1_1 like Mac OS X) AppleWebKit/533.0 (KHTML, like Gecko) CriOS/51.0.844.0 Mobile/22B509 Safari/533.0'),
 Result(user_agent=UserAgent(family='Opera', major='8', minor='11', patch=None, patch_minor=None), os=OS(family='Windows', major='ME', minor=None, patch=None, patch_minor=None), device=None, string='Opera/8.11.(Windows 98; Win 9x 4.90; da-DK) Presto/2.9.177 Version/10.00'),
 Result(user_agent=UserAgent(family='Firefox Mobile', major='22', minor='0', patch=None, patch_minor=None), os=OS(family='Android', major='7', minor='1', patch=None, patch_minor=None), device=Device(family='Generic Smartphone', brand='Generic', model='Smartphone'), string='Mozilla/5.0 (Android 7.1; Mobile; rv:22.0) Gecko/22.0 Firefox/22.0'),
 Result(user_agent=UserAgent(family='Safari', major='4', minor='0', patch=None, patch_minor=None), os=OS(family='Windows', major='Vista', minor=None, patch=None, patch_minor=None), device=None, string='Mozilla/5.0 (Windows; U; Windows NT 6.0) AppleWebKit/533.28.5 (KHTML, like Gecko) Version/4.0 Safari/533.28.5'),
 Result(user_agent=UserAgent(family='Firefox iOS', major='18', minor='1', patch=None, patch_minor=None), os=OS(family='iOS', major='12', minor='4', patch='8', patch_minor=None), device=Device(family='iPhone', brand='Apple', model='iPhone'), string='Mozilla/5.0 (iPhone; CPU iPhone OS 12_4_8 like Mac OS X) AppleWebKit/533.2 (KHTML, like Gecko) FxiOS/18.1i4735.0 Mobile/92M384 Safari/533.2'),
 Result(user_agent=UserAgent(family='IE', major='5', minor='0', patch=None, patch_minor=None), os=OS(family='Windows', major='95', minor=None, patch=None, patch_minor=None), device=None, string='Mozilla/5.0 (compatible; MSIE 5.0; Windows 95; Trident/5.1)'),
 Result(user_agent=UserAgent(family='Chrome', major='32', minor='0', patch='844', patch_minor='0'), os=OS(family='Mac OS X', major='10', minor='12', patch='1', patch_minor=None), device=Device(family='Mac', brand='Apple', model='Mac'), string='Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/532.1 (KHTML, like Gecko) Chrome/32.0.844.0 Safari/532.1')]

In [11]:
# Test code if object value is None, to avoid error of filling attributes 
parsedURL = parse("Mozilla/5.0 (compatible; MSIE 8.0; Windows NT 6.2; Trident/5.0")
parsedURL2 = parse("Mozilla/5.0 (Macintosh; PPC Mac OS X 10_11_5; rv:1.9.6.20) Gecko/2583-02-14 13:30:10 Firefox/11.0")
if parsedURL2.__getattribute__('device') is not pd.NA:
    test = parsedURL2.__getattribute__('device').family
test

'Mac'

In [12]:
# Test with one row before applying to df
test = parse(df.loc[0, "Device Information"])
browser_family = test.__getattribute__('user_agent').family
browser_family

'IE'

In [13]:
# Split Device Information to Browser, OS and Device more detailed information
# Should we separate browser_family and browser-major or keep together?
df['Browser_family'] = df['Device Information'].apply(lambda x: parse(x).__getattribute__('user_agent').family if parse(x).__getattribute__('user_agent') is not None else pd.NA)
df['Browser_major'] = df['Device Information'].apply(lambda x: parse(x).__getattribute__('user_agent').major if parse(x).__getattribute__('user_agent') is not None else pd.NA)
df['OS_family'] = df['Device Information'].apply(lambda x: parse(x).__getattribute__('os').family if parse(x).__getattribute__('os') is not None else pd.NA)
df['OS_major'] = df['Device Information'].apply(lambda x: parse(x).__getattribute__('os').major if parse(x).__getattribute__('os') is not None else pd.NA)
df['Device_family'] = df['Device Information'].apply(lambda x: parse(x).__getattribute__('device').family if parse(x).__getattribute__('device') is not None else pd.NA)
df['Device_brand'] = df['Device Information'].apply(lambda x: parse(x).__getattribute__('device').brand if parse(x).__getattribute__('device') is not None else pd.NA)

In [14]:
df.head(5)

,Timestamp,Source IP Address,Destination IP Address,Source Port,Destination Port,Protocol,Packet Length,Packet Type,Traffic Type,Payload Data,...,Proxy Information,Firewall Logs,IDS/IPS Alerts,Log Source,Browser_family,Browser_major,OS_family,OS_major,Device_family,Device_brand
0,2023-05-30 06:33:58,103.216.15.12,84.9.164.252,31225,17616,ICMP,503,Data,HTTP,Qui natus odio asperiores nam. Optio nobis ius...,...,150.9.97.135,Log Data,NaN,Server,IE,9,Windows,8,<NA>,<NA>
1,2020-08-26 07:08:30,78.199.217.198,66.191.137.154,17245,48166,ICMP,1174,Data,HTTP,Aperiam quos modi officiis veritatis rem. Omni...,...,NaN,Log Data,NaN,Firewall,IE,8,Windows,Vista,<NA>,<NA>
2,2022-11-13 08:23:25,63.79.210.48,198.219.82.17,16811,53600,UDP,306,Control,HTTP,Perferendis sapiente vitae soluta. Hic delectu...,...,114.133.48.179,Log Data,Alert Data,Firewall,IE,9,Windows,8,<NA>,<NA>
3,2023-07-02 10:38:46,163.42.196.10,101.228.192.255,20018,32534,UDP,385,Data,HTTP,Totam maxime beatae expedita explicabo porro l...,...,NaN,NaN,Alert Data,Firewall,Firefox,11,Mac OS X,10,Mac,Apple
4,2023-07-16 13:11:07,71.166.185.76,189.243.174.238,6131,26646,TCP,1462,Data,DNS,Odit nesciunt dolorem nisi iste iusto. Animi v...,...,149.6.110.119,NaN,Alert Data,Firewall,IE,5,Windows,8,<NA>,<NA>

In [15]:
df.isna().sum()

Timestamp                     0
Source IP Address             0
Destination IP Address        0
Source Port                   0
Destination Port              0
Protocol                      0
Packet Length                 0
Packet Type                   0
Traffic Type                  0
Payload Data                  0
Malware Indicators        20000
Anomaly Scores                0
Alerts/Warnings           20067
Attack Type                   0
Attack Signature              0
Action Taken                  0
Severity Level                0
User Information              0
Device Information            0
Network Segment               0
Geo-location Data             0
Proxy Information         19851
Firewall Logs             19961
IDS/IPS Alerts            20050
Log Source                    0
Browser_family                0
Browser_major                 0
OS_family                     0
OS_major                   7171
Device_family             23678
Device_brand              23678
dtype: int64

In [ ]:
# display non-numeric columns for team distribution tasks (working on categorical features)
df.select_dtypes(exclude=[np.number]).columns.tolist()

In [16]:
# ASK: only 1 destionation IP appears in source IPs, what does this mean? cause both looks inbound traffic.
# find destination IPs that appear in Source IPs without modifying df
destIPinSourceIP = df['Destination IP Address'].isin(df['Source IP Address'])
matched_rows = df[destIPinSourceIP].copy()  # recuperate whole rows
matched_rows

# df.drop(columns=['Dest_in_Source'])

,Timestamp,Source IP Address,Destination IP Address,Source Port,Destination Port,Protocol,Packet Length,Packet Type,Traffic Type,Payload Data,...,Proxy Information,Firewall Logs,IDS/IPS Alerts,Log Source,Browser_family,Browser_major,OS_family,OS_major,Device_family,Device_brand
2919,2022-12-05 04:14:32,130.181.86.38,200.139.187.115,54484,31019,UDP,454,Data,HTTP,Unde tempore iusto dolore officiis excepturi. ...,...,NaN,NaN,Alert Data,Server,IE,9,Windows,NT,<NA>,<NA>

In [ ]:
# take the first three octets of the IP as a list
split = "103.216.15.12".split(".")[:3]
ip3 = ".".join(split)
ip3

In [17]:
# Split all IPs to /24 subnet ==> local subnet/Single host
def splitIP24(ip):
    if pd.isna(ip):
        return pd.NA
    return ".".join(ip.split(".")[:3])

# Split all IPs to /16 subnet ==> network owner/region (ISP/backbone provider)
def splitIP16(ip):
    if pd.isna(ip):
        return pd.NA
    return ".".join(ip.split(".")[:2])

df['Source IP Address_24'] = df['Source IP Address'].apply(splitIP24)
df['Source IP Address_16'] = df['Source IP Address'].apply(splitIP16)

df['Destination IP Address_24'] = df['Destination IP Address'].apply(splitIP24)
df['Destination IP Address_16'] = df['Destination IP Address'].apply(splitIP16)

df['Proxy Information_24'] = df['Proxy Information'].apply(splitIP24)
df['Proxy Information_16'] = df['Proxy Information'].apply(splitIP16)

df.head(2)

,Timestamp,Source IP Address,Destination IP Address,Source Port,Destination Port,Protocol,Packet Length,Packet Type,Traffic Type,Payload Data,...,OS_family,OS_major,Device_family,Device_brand,Source IP Address_24,Source IP Address_16,Destination IP Address_24,Destination IP Address_16,Proxy Information_24,Proxy Information_16
0,2023-05-30 06:33:58,103.216.15.12,84.9.164.252,31225,17616,ICMP,503,Data,HTTP,Qui natus odio asperiores nam. Optio nobis ius...,...,Windows,8,<NA>,<NA>,103.216.15,103.216,84.9.164,84.9,150.9.97,150.9
1,2020-08-26 07:08:30,78.199.217.198,66.191.137.154,17245,48166,ICMP,1174,Data,HTTP,Aperiam quos modi officiis veritatis rem. Omni...,...,Windows,Vista,<NA>,<NA>,78.199.217,78.199,66.191.137,66.191,<NA>,<NA>

In [18]:
# Check private range
# • 10.0.0.0 – 10.255.255.255 
# • 172.16.0.0 – 172.31.255.255 
# • 192.168.0.0 – 192.168.255.255

def isPrivateIP(ip):
    if pd.isna(ip):
        return pd.NA
    octets = ip.split(".")
    first = int(octets[0])
    second = int(octets[1])
    if first == 10:
        return True
    elif first == 172 and 16 <= second <= 31:
        return True
    elif first == 192 and second == 168:
        return True
    else:
        return False

df['Source_IP_Private'] = df['Source IP Address'].apply(isPrivateIP)
df['Destination_IP_Private'] = df['Destination IP Address'].apply(isPrivateIP)
df['Proxy_IP_Private'] = df['Proxy Information'].apply(isPrivateIP)

df.head(10)

,Timestamp,Source IP Address,Destination IP Address,Source Port,Destination Port,Protocol,Packet Length,Packet Type,Traffic Type,Payload Data,...,Device_brand,Source IP Address_24,Source IP Address_16,Destination IP Address_24,Destination IP Address_16,Proxy Information_24,Proxy Information_16,Source_IP_Private,Destination_IP_Private,Proxy_IP_Private
0,2023-05-30 06:33:58,103.216.15.12,84.9.164.252,31225,17616,ICMP,503,Data,HTTP,Qui natus odio asperiores nam. Optio nobis ius...,...,<NA>,103.216.15,103.216,84.9.164,84.9,150.9.97,150.9,False,False,False
1,2020-08-26 07:08:30,78.199.217.198,66.191.137.154,17245,48166,ICMP,1174,Data,HTTP,Aperiam quos modi officiis veritatis rem. Omni...,...,<NA>,78.199.217,78.199,66.191.137,66.191,<NA>,<NA>,False,False,<NA>
2,2022-11-13 08:23:25,63.79.210.48,198.219.82.17,16811,53600,UDP,306,Control,HTTP,Perferendis sapiente vitae soluta. Hic delectu...,...,<NA>,63.79.210,63.79,198.219.82,198.219,114.133.48,114.133,False,False,False
3,2023-07-02 10:38:46,163.42.196.10,101.228.192.255,20018,32534,UDP,385,Data,HTTP,Totam maxime beatae expedita explicabo porro l...,...,Apple,163.42.196,163.42,101.228.192,101.228,<NA>,<NA>,False,False,<NA>
4,2023-07-16 13:11:07,71.166.185.76,189.243.174.238,6131,26646,TCP,1462,Data,DNS,Odit nesciunt dolorem nisi iste iusto. Animi v...,...,<NA>,71.166.185,71.166,189.243.174,189.243,149.6.110,149.6,False,False,False
5,2022-10-28 13:14:27,198.102.5.160,147.190.155.133,17430,52805,UDP,1423,Data,HTTP,Repellat quas illum harum fugit incidunt exerc...,...,<NA>,198.102.5,198.102,147.190.155,147.190,<NA>,<NA>,False,False,<NA>
6,2022-05-16 17:55:43,97.253.103.59,77.16.101.53,26562,17416,TCP,379,Data,DNS,Qui numquam inventore repellat ratione fugit o...,...,<NA>,97.253.103,97.253,77.16.101,77.16,<NA>,<NA>,False,False,<NA>
7,2023-02-12 07:13:17,11.48.99.245,178.157.14.116,34489,20396,ICMP,1022,Data,DNS,Amet libero optio quidem praesentium libero. E...,...,Apple,11.48.99,11.48,178.157.14,178.157,192.31.159,192.31,False,False,False
8,2023-06-27 11:02:56,49.32.208.167,72.202.237.9,56296,20857,TCP,1281,Control,FTP,Veritatis nihil amet atque molestias aperiam m...,...,Apple,49.32.208,49.32,72.202.237,72.202,<NA>,<NA>,False,False,<NA>
9,2021-08-15 22:29:04,114.109.149.113,160.88.194.172,37918,50039,UDP,224,Data,HTTP,Consequatur ipsum autem reprehenderit quae. Do...,...,<NA>,114.109.149,114.109,160.88.194,160.88,87.128.245,87.128,False,False,False

In [ ]:
df

In [19]:
with geoip2.database.Reader('./data/ext/GeoLite2-Country_20251212/GeoLite2-Country.mmdb') as reader:
    response = reader.country(df.loc[0, 'Source IP Address'])
    print(response)
    # print(response.continent.names)

geoip2.models.Country({'continent': {'code': 'AS', 'geoname_id': 6255147, 'names': {'de': 'Asien', 'en': 'Asia', 'es': 'Asia', 'fr': 'Asie', 'ja': 'アジア', 'pt-BR': 'Ásia', 'ru': 'Азия', 'zh-CN': '亚洲'}}, 'country': {'geoname_id': 1814991, 'iso_code': 'CN', 'names': {'de': 'China', 'en': 'China', 'es': 'China', 'fr': 'Chine', 'ja': '中国', 'pt-BR': 'China', 'ru': 'Китай', 'zh-CN': '中国'}}, 'registered_country': {'geoname_id': 1814991, 'iso_code': 'CN', 'names': {'de': 'China', 'en': 'China', 'es': 'China', 'fr': 'Chine', 'ja': '中国', 'pt-BR': 'China', 'ru': 'Китай', 'zh-CN': '中国'}}, 'traits': {'ip_address': '103.216.15.12', 'prefix_len': 21}}, ['en'])

In [20]:
df_test = df.head(2)
df_test

,Timestamp,Source IP Address,Destination IP Address,Source Port,Destination Port,Protocol,Packet Length,Packet Type,Traffic Type,Payload Data,...,Device_brand,Source IP Address_24,Source IP Address_16,Destination IP Address_24,Destination IP Address_16,Proxy Information_24,Proxy Information_16,Source_IP_Private,Destination_IP_Private,Proxy_IP_Private
0,2023-05-30 06:33:58,103.216.15.12,84.9.164.252,31225,17616,ICMP,503,Data,HTTP,Qui natus odio asperiores nam. Optio nobis ius...,...,<NA>,103.216.15,103.216,84.9.164,84.9,150.9.97,150.9,False,False,False
1,2020-08-26 07:08:30,78.199.217.198,66.191.137.154,17245,48166,ICMP,1174,Data,HTTP,Aperiam quos modi officiis veritatis rem. Omni...,...,<NA>,78.199.217,78.199,66.191.137,66.191,<NA>,<NA>,False,False,<NA>

In [32]:
import geoip2.errors
with geoip2.database.Reader('./data/ext/GeoLite2-Country_20251212/GeoLite2-Country.mmdb') as reader:
    def _lookup_ip(ip):
        # 1. Handle missing/NA values
        if not ip or pd.isna(ip):
            return {
                'ContinentName': pd.NA,
                'CountryName': pd.NA,
            }
        
        # 2. Perform external lookup
        try:
            response = reader.country(ip)
            
            # 3. RETURN A DICTIONARY of all desired features
            return {
                'ContinentName': response.continent.name,
                'CountryName': response.country.name,
            }
        
        except geoip2.errors.AddressNotFoundError:
            # 4. Return NA dictionary for not found IPs
            return {
                'ContinentName': pd.NA,
                'CountryName': pd.NA,
                # 'ASN': pd.NA,
                # 'Is_Private': False
            }
        except Exception:
            # 5. Return NA dictionary for other errors
            return {
                'ContinentNamee': pd.NA,
                'CountryName': pd.NA,
                # 'ASN': pd.NA,
                # 'Is_Private': False
            }

    # --- Applying the Function ---
    geo_results_sourceIP = df['Source IP Address'].apply(_lookup_ip)
    geo_results_destIP = df['Destination IP Address'].apply(_lookup_ip)
    geo_results_proxyIP = df['Proxy Information'].apply(_lookup_ip)

    # print('geo_results_sourceIP', geo_results_sourceIP)
    # Convert list of dictionaries to DataFrame
    geo_df_sourceIP = pd.DataFrame(geo_results_sourceIP.tolist(), index=geo_results_sourceIP.index)
    # print('geo_df_sourceIP', geo_df_sourceIP)
    geo_df_destIP = pd.DataFrame(geo_results_destIP.tolist(), index=geo_results_destIP.index)
    print('geo_df_destIP', geo_df_destIP)

    geo_df_proxyIP = pd.DataFrame(geo_results_proxyIP.tolist(), index=geo_results_proxyIP.index)

    # test to df_test before real df
    # df_test.loc[:, ('ContinentName_Source', 'CountryName_Source')] = geo_df_sourceIP[['ContinentName', 'CountryName']]
    # Source IP
    df['ContinentName_Source'] = geo_df_sourceIP['ContinentName']
    df['CountryName_Source'] = geo_df_sourceIP['CountryName']
    # df.loc[:, ('ContinentName_Source', 'CountryName_Source')] = geo_df_sourceIP[['ContinentName', 'CountryName']]
    # print('am here')
    
    # Destination IP
    df['ContinentName_Destination'] = geo_df_destIP['ContinentName']
    df['CountryName_Destination'] = geo_df_destIP['CountryName']

    # Proxy IP
    df['ContinentName_Proxy'] = geo_df_proxyIP['ContinentName']
    df['CountryName_Proxy'] = geo_df_proxyIP['CountryName']

geo_df_destIP        ContinentName     CountryName
0             Europe  United Kingdom
1      North America   United States
2      North America   United States
3               Asia           China
4      North America          Mexico
...              ...             ...
39995           Asia     South Korea
39996         Africa           Kenya
39997  North America   United States
39998  North America   United States
39999           Asia         Türkiye

[40000 rows x 2 columns]

In [33]:
# test to df_test before real df
# df_test
df.head(5)

,Timestamp,Source IP Address,Destination IP Address,Source Port,Destination Port,Protocol,Packet Length,Packet Type,Traffic Type,Payload Data,...,Proxy Information_16,Source_IP_Private,Destination_IP_Private,Proxy_IP_Private,ContinentName_Source,CountryName_Source,ContinentName_Destination,CountryName_Destination,ContinentName_Proxy,CountryName_Proxy
0,2023-05-30 06:33:58,103.216.15.12,84.9.164.252,31225,17616,ICMP,503,Data,HTTP,Qui natus odio asperiores nam. Optio nobis ius...,...,150.9,False,False,False,Asia,China,Europe,United Kingdom,Asia,Japan
1,2020-08-26 07:08:30,78.199.217.198,66.191.137.154,17245,48166,ICMP,1174,Data,HTTP,Aperiam quos modi officiis veritatis rem. Omni...,...,<NA>,False,False,<NA>,Europe,France,North America,United States,<NA>,<NA>
2,2022-11-13 08:23:25,63.79.210.48,198.219.82.17,16811,53600,UDP,306,Control,HTTP,Perferendis sapiente vitae soluta. Hic delectu...,...,114.133,False,False,False,North America,United States,North America,United States,Asia,Malaysia
3,2023-07-02 10:38:46,163.42.196.10,101.228.192.255,20018,32534,UDP,385,Data,HTTP,Totam maxime beatae expedita explicabo porro l...,...,<NA>,False,False,<NA>,Asia,Japan,Asia,China,<NA>,<NA>
4,2023-07-16 13:11:07,71.166.185.76,189.243.174.238,6131,26646,TCP,1462,Data,DNS,Odit nesciunt dolorem nisi iste iusto. Animi v...,...,149.6,False,False,False,North America,United States,North America,Mexico,North America,United States

In [34]:
with geoip2.database.Reader('./data/ext/GeoLite2-City_20251212/GeoLite2-City.mmdb') as reader:
    response = reader.city(df.loc[0, 'Source IP Address'])
    print(response)
    print(response.city.name)
    print(response.location.latitude)
    print(response.location.longitude)
    # print(response.postal.code)

geoip2.models.City({'continent': {'code': 'AS', 'geoname_id': 6255147, 'names': {'de': 'Asien', 'en': 'Asia', 'es': 'Asia', 'fr': 'Asie', 'ja': 'アジア', 'pt-BR': 'Ásia', 'ru': 'Азия', 'zh-CN': '亚洲'}}, 'country': {'geoname_id': 1814991, 'iso_code': 'CN', 'names': {'de': 'China', 'en': 'China', 'es': 'China', 'fr': 'Chine', 'ja': '中国', 'pt-BR': 'China', 'ru': 'Китай', 'zh-CN': '中国'}}, 'location': {'accuracy_radius': 1000, 'latitude': 34.7732, 'longitude': 113.722, 'time_zone': 'Asia/Shanghai'}, 'registered_country': {'geoname_id': 1814991, 'iso_code': 'CN', 'names': {'de': 'China', 'en': 'China', 'es': 'China', 'fr': 'Chine', 'ja': '中国', 'pt-BR': 'China', 'ru': 'Китай', 'zh-CN': '中国'}}, 'traits': {'ip_address': '103.216.15.12', 'prefix_len': 21}}, ['en'])
None
34.7732
113.722

In [38]:
import geoip2.errors
with geoip2.database.Reader('./data/ext/GeoLite2-City_20251212/GeoLite2-City.mmdb') as reader:
    def _lookup_ip(ip):
        # 1. Handle missing/NA values
        if not ip or pd.isna(ip):
            return {
                'CityName': pd.NA,
                'CityLat_Source': pd.NA,
                'CityLon': pd.NA,
            }
        
        # 2. Perform external lookup
        try:
            response = reader.city(ip)
            
            # 3. RETURN A DICTIONARY of all desired features
            return {
                    'CityName': response.city.name,
                    'CityLat': response.location.latitude,
                    'CityLon': response.location.longitude,
            }
        
        except geoip2.errors.AddressNotFoundError:
            # 4. Return NA dictionary for not found IPs
            return {
                'CityName': pd.NA,
                'CityLat': pd.NA,
                'CityLon': pd.NA,
                # 'ASN': pd.NA,
                # 'Is_Private': False
            }
        except Exception:
            # 5. Return NA dictionary for other errors
            return {
                'CityName': pd.NA,
                'CityLat': pd.NA,
                'CityLon': pd.NA,
                # 'ASN': pd.NA,
                # 'Is_Private': False
            }

    # --- Applying the Function ---
    geo_results_sourceIP = df['Source IP Address'].apply(_lookup_ip)
    geo_results_destIP = df['Destination IP Address'].apply(_lookup_ip)
    geo_results_proxyIP = df['Proxy Information'].apply(_lookup_ip)

    # print(geo_results_sourceIP)
    # Convert list of dictionaries to DataFrame
    geo_df_sourceIP = pd.DataFrame(geo_results_sourceIP.tolist(), index=geo_results_sourceIP.index)
    geo_df_destIP = pd.DataFrame(geo_results_destIP.tolist(), index=geo_results_destIP.index)
    geo_df_proxyIP = pd.DataFrame(geo_results_proxyIP.tolist(), index=geo_results_proxyIP.index)
    # print(geo_df_sourceIP)

    # test to df_test before real df
    # df_test.loc[:, ('CityName_Source', 'CityLat_Source', 'CityLon_Source')] = geo_df[['CityName_Source', 'CityLat_Source', 'CityLon_Source']]
    df['CityName_Proxy'] = geo_df_proxyIP['CityName']
    df['CityLat_Proxy'] = geo_df_proxyIP['CityLat']
    df['CityLon_Proxy'] = geo_df_proxyIP['CityLon']

    df['CityName_Destination'] = geo_df_destIP['CityName']
    df['CityLat_Destination'] = geo_df_destIP['CityLat']
    df['CityLon_Destination'] = geo_df_destIP['CityLon']

    df['CityName_Source'] = geo_df_sourceIP['CityName']
    df['CityLat_Source'] = geo_df_sourceIP['CityLat']
    df['CityLon_Source'] = geo_df_sourceIP['CityLon']

    # why codes below didnt work??
    # df.loc[:, ('CityName_Source', 'CityLat_Source', 'CityLon_Source')] = geo_df_sourceIP[['CityName', 'CityLat', 'CityLon']]
    # df.loc[:, ('CityName_Destination', 'CityLat_Destination', 'CityLon_Destination')] = geo_df_destIP[['CityName', 'CityLat', 'CityLon']]
    # df.loc[:, ('CityName_Proxy', 'CityLat_Proxy', 'CityLon_Proxy')] = geo_df_proxyIP[['CityName', 'CityLat', 'CityLon']]

In [39]:
# test to df_test before real df
# df_test
df.head(5)

,Timestamp,Source IP Address,Destination IP Address,Source Port,Destination Port,Protocol,Packet Length,Packet Type,Traffic Type,Payload Data,...,CountryName_Proxy,CityName_Source,CityLat_Source,CityLon_Source,CityName_Destination,CityLat_Destination,CityLon_Destination,CityName_Proxy,CityLat_Proxy,CityLon_Proxy
0,2023-05-30 06:33:58,103.216.15.12,84.9.164.252,31225,17616,ICMP,503,Data,HTTP,Qui natus odio asperiores nam. Optio nobis ius...,...,Japan,None,34.7732,113.722,Cheltenham,51.9698,-1.8666,Kyoto,35.0231,135.752
1,2020-08-26 07:08:30,78.199.217.198,66.191.137.154,17245,48166,ICMP,1174,Data,HTTP,Aperiam quos modi officiis veritatis rem. Omni...,...,<NA>,Paris,48.8558,2.3494,Rochester,44.0484,-92.4948,<NA>,NaN,<NA>
2,2022-11-13 08:23:25,63.79.210.48,198.219.82.17,16811,53600,UDP,306,Control,HTTP,Perferendis sapiente vitae soluta. Hic delectu...,...,Malaysia,None,37.751,-97.822,None,37.751,-97.822,None,2.5,112.5
3,2023-07-02 10:38:46,163.42.196.10,101.228.192.255,20018,32534,UDP,385,Data,HTTP,Totam maxime beatae expedita explicabo porro l...,...,<NA>,None,35.69,139.69,Shanghai,31.2222,121.4581,<NA>,NaN,<NA>
4,2023-07-16 13:11:07,71.166.185.76,189.243.174.238,6131,26646,TCP,1462,Data,DNS,Odit nesciunt dolorem nisi iste iusto. Animi v...,...,United States,Towson,39.4091,-76.5991,Morelia,19.6648,-101.2796,None,37.751,-97.822

In [40]:
df

,Timestamp,Source IP Address,Destination IP Address,Source Port,Destination Port,Protocol,Packet Length,Packet Type,Traffic Type,Payload Data,...,CountryName_Proxy,CityName_Source,CityLat_Source,CityLon_Source,CityName_Destination,CityLat_Destination,CityLon_Destination,CityName_Proxy,CityLat_Proxy,CityLon_Proxy
0,2023-05-30 06:33:58,103.216.15.12,84.9.164.252,31225,17616,ICMP,503,Data,HTTP,Qui natus odio asperiores nam. Optio nobis ius...,...,Japan,None,34.7732,113.722,Cheltenham,51.9698,-1.8666,Kyoto,35.0231,135.752
1,2020-08-26 07:08:30,78.199.217.198,66.191.137.154,17245,48166,ICMP,1174,Data,HTTP,Aperiam quos modi officiis veritatis rem. Omni...,...,<NA>,Paris,48.8558,2.3494,Rochester,44.0484,-92.4948,<NA>,NaN,<NA>
2,2022-11-13 08:23:25,63.79.210.48,198.219.82.17,16811,53600,UDP,306,Control,HTTP,Perferendis sapiente vitae soluta. Hic delectu...,...,Malaysia,None,37.751,-97.822,None,37.751,-97.822,None,2.5,112.5
3,2023-07-02 10:38:46,163.42.196.10,101.228.192.255,20018,32534,UDP,385,Data,HTTP,Totam maxime beatae expedita explicabo porro l...,...,<NA>,None,35.69,139.69,Shanghai,31.2222,121.4581,<NA>,NaN,<NA>
4,2023-07-16 13:11:07,71.166.185.76,189.243.174.238,6131,26646,TCP,1462,Data,DNS,Odit nesciunt dolorem nisi iste iusto. Animi v...,...,United States,Towson,39.4091,-76.5991,Morelia,19.6648,-101.2796,None,37.751,-97.822
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39995,2023-05-26 14:08:42,26.36.109.26,121.100.75.240,31005,6764,UDP,1428,Control,HTTP,Quibusdam ullam consequatur consequuntur accus...,...,<NA>,None,37.751,-97.822,Chuncheon,37.8738,127.727,<NA>,NaN,<NA>
39996,2023-03-27 00:38:27,17.21.163.81,196.108.134.78,2553,28091,UDP,1184,Control,HTTP,Quaerat neque esse. Animi expedita natus commo...,...,Malaysia,New York,40.7126,-74.0066,None,1.0,38.0,Batu Caves,3.2248,101.678
39997,2022-03-31 01:45:49,162.35.217.57,98.107.0.15,22505,25152,UDP,1043,Data,DNS,Enim at aspernatur illum. Saepe numquam eligen...,...,<NA>,None,37.751,-97.822,None,37.751,-97.822,<NA>,NaN,<NA>
39998,2023-09-22 18:32:38,208.72.233.205,173.79.112.252,20013,2703,UDP,483,Data,FTP,Officiis dolorem sed harum provident earum dis...,...,<NA>,None,37.751,-97.822,Sterling,39.0503,-77.3909,<NA>,<NA>,<NA>
39999,2023-10-10 11:59:52,14.102.21.108,109.198.45.7,50137,55575,ICMP,1175,Control,HTTP,Eligendi omnis voluptate nihil voluptatibus do...,...,South Korea,None,37.751,-97.822,None,41.0146,28.9532,Gangnam-gu,37.5093,127.0465

In [ ]:
# Treat ports
# HTTPS 443, SSH 22, DNS 53, FTP 20-21) 
# User/Registered Ports (1024-49151): used by Server, Application, Database, VPN (HTTP alternate 8080, MySQL 3306) 
# Dynamic and/or Private Ports (49152-65535): temporary/ephemeral ports for outgoing connections, used by Clients. Rapid rotation may signal botnets. 
# Plot to see distribution of these different ports vs packet length 
# Also vs protocol/traffic type/attack type, etc ? Any meaning?

In [ ]:
# How to treat timestamps?
# Timeseries?

In [ ]:
df.corr(numeric_only=True)

In [ ]:
cols_to_check = [
    "Attack Signature",
    "Severity Level",
    "Action Taken",
    "IDS/IPS Alerts",
    "Malware Indicators",
    "Alerts/Warnings",
    "Network Segment",
    "Firewall Logs",
    "Log Source"
]
for col in cols_to_check:
    print(f"\n--- {col} ---")
    print(df.groupby('Attack Type')[col].value_counts(dropna=False))

In [ ]:
# is it good news cause our model won't have bias for this colums cause it has pretty  fair distribution? or there is other meaning?
df.groupby('Attack Type')['Firewall Logs'].value_counts()

In [ ]:
df.groupby('Attack Type')['Firewall Logs'].value_counts(dropna=False)

In [ ]:
# is it good news cause our model won't have bias for this colums cause it has pretty  fair distribution? or there is other meaning?
df.groupby('Attack Type')['Alerts/Warnings'].value_counts()

In [ ]:
df.groupby('Attack Type')['Alerts/Warnings'].value_counts(dropna=False)

In [ ]:
# is it good news cause our model won't have bias for this colums cause it has pretty  fair distribution? or there is other meaning?
df.groupby('Attack Type')['Malware Indicators'].value_counts()

In [ ]:
df.groupby('Attack Type')['Malware Indicators'].value_counts(dropna=False)

In [ ]:
df.groupby('Attack Type')['IDS/IPS Alerts'].value_counts()

In [ ]:
df.groupby('Attack Type')['IDS/IPS Alerts'].value_counts(dropna=False)

In [ ]:
sns.histplot(x="Malware Indicators",hue="Attack Type",multiple="stack", data=df)
plt.show()

In [ ]:
df.groupby('Attack Type')['Firewall Logs'].value_counts()

In [ ]:
# entropy doesn't make any sense as the payload data seems like synthetic (need to check with Hanna).
from collections import Counter

def entropy_bytes(s):
    b = str(s).encode('utf-8', errors='ignore')
    if not b: return 0.0
    counts = Counter(b)
    total = len(b)
    return -sum((c/total) * math.log2(c/total) for c in counts.values())

df['Entropy'] = df['Payload Data'].apply(entropy_bytes)
df['Band'] = df['Entropy'].apply(lambda e: 'High' if e > 7 else ('Medium' if e >= 5 else 'Low'))
print(df['Band'].value_counts())

In [ ]:
df.groupby('Attack Type')['Packet Length'].describe()

In [ ]:
# doesn't show spike of Blocked if Severity Level is High
df.groupby(['Attack Type', 'Severity Level'])['Action Taken'].value_counts()

In [ ]:
# Doesn't show that IDS/IPS Alert trigger Alerts/Warnings
df.groupby('IDS/IPS Alerts')['Alerts/Warnings'].value_counts(dropna=False)

In [ ]:
# Doesn't show that certain signature is assigned to attack type
df.groupby('Attack Type')['Attack Signature'].value_counts(dropna=False)