### Choose model and evaluation to try
#### Classification => model has to choose a class among many (fixed number of classes and classes are known)
#### Models:
#### Simple (linear): Logistic regression
#### Complex (non-linear): Decision tree, Random Forest, and MLPs

### Evaluation - Precision, Recall or F1-Score?

In [1]:
from sklearn.model_selection import train_test_split

In [2]:
import pandas as pd
import sys
import os
import numpy as np

# Get the parent directory of the notebooks folder
notebook_dir = os.path.dirname(os.path.abspath('__file__'))
parent_dir = os.path.dirname(notebook_dir)
sys.path.insert(0, parent_dir)

In [3]:
# Load dataset1_finalfeatures
df = pd.read_csv('../data/processed_data/cybersecurity_attacks_dataset1_finalfeatures.csv')

In [4]:
df

,Attack Type,Severity Level,Packet Length_Quartile,Anomaly Scores_Quartile,Packet Type_Data,Malware Indicators_1,Alerts/Warnings_1,Attack Signature_Known Pattern B,Firewall Logs_1,IDS/IPS Alerts_1,...,Browser_family_Opera,Browser_family_Other,Browser_family_Safari,OS_family_Linux,OS_family_Mac OS X,OS_family_Windows,OS_family_iOS,Device_type_PC,Device_type_Tablet,Device_type_Unknown
0,3,0,1,1,True,True,False,True,True,False,...,False,False,False,False,False,True,False,True,False,False
1,3,0,3,2,True,True,False,False,True,False,...,False,False,False,False,False,True,False,True,False,False
2,1,0,0,3,False,True,True,True,True,True,...,False,False,False,False,False,True,False,True,False,False
3,3,1,0,0,True,False,True,True,False,True,...,False,False,False,False,True,False,False,True,False,False
4,1,0,3,0,True,False,True,True,False,True,...,False,False,False,False,False,True,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39995,1,1,3,1,False,True,False,False,True,True,...,False,True,False,False,False,False,True,False,True,False
39996,1,2,3,1,False,True,False,False,True,False,...,False,False,True,False,False,True,False,True,False,False
39997,1,0,2,1,True,True,False,True,True,True,...,False,False,True,False,False,True,False,True,False,False
39998,3,0,1,3,True,True,True,True,True,False,...,False,False,False,True,False,False,False,True,False,False
39999,2,1,3,1,False,False,True,True,True,True,...,False,True,False,False,False,False,True,False,False,False

In [5]:
df.nunique()

Attack Type                                3
Severity Level                             3
Packet Length_Quartile                     4
Anomaly Scores_Quartile                    4
Packet Type_Data                           2
Malware Indicators_1                       2
Alerts/Warnings_1                          2
Attack Signature_Known Pattern B           2
Firewall Logs_1                            2
IDS/IPS Alerts_1                           2
Log Source_Server                          2
is_weekend_1                               2
Protocol_TCP                               2
Protocol_UDP                               2
Traffic Type_FTP                           2
Traffic Type_HTTP                          2
Action Taken_Ignored                       2
Action Taken_Logged                        2
Network Segment_Segment B                  2
Network Segment_Segment C                  2
hours_div_6-20                             2
ContinentName_Source_Europe                2
ContinentName_Source_North America         2
ContinentName_Source_Other                 2
ContinentName_Destination_Europe           2
ContinentName_Destination_North America    2
ContinentName_Destination_Other            2
ContinentName_Proxy_North America          2
ContinentName_Proxy_Other                  2
ContinentName_Proxy_noProxy                2
Source IP_Class_B                          2
Source IP_Class_C                          2
Destination IP_Class_B                     2
Destination IP_Class_C                     2
Proxy_Class_B                              2
Proxy_Class_C                              2
Proxy_Class_noProxy                        2
Source Port_Cat_Registered                 2
Destination Port_Cat_Registered            2
Browser_family_Firefox                     2
Browser_family_IE                          2
Browser_family_Opera                       2
Browser_family_Other                       2
Browser_family_Safari                      2
OS_family_Linux                            2
OS_family_Mac OS X                         2
OS_family_Windows                          2
OS_family_iOS                              2
Device_type_PC                             2
Device_type_Tablet                         2
Device_type_Unknown                        2
dtype: int64

In [6]:
df.isna().sum()

Attack Type                                0
Severity Level                             0
Packet Length_Quartile                     0
Anomaly Scores_Quartile                    0
Packet Type_Data                           0
Malware Indicators_1                       0
Alerts/Warnings_1                          0
Attack Signature_Known Pattern B           0
Firewall Logs_1                            0
IDS/IPS Alerts_1                           0
Log Source_Server                          0
is_weekend_1                               0
Protocol_TCP                               0
Protocol_UDP                               0
Traffic Type_FTP                           0
Traffic Type_HTTP                          0
Action Taken_Ignored                       0
Action Taken_Logged                        0
Network Segment_Segment B                  0
Network Segment_Segment C                  0
hours_div_6-20                             0
ContinentName_Source_Europe                0
ContinentName_Source_North America         0
ContinentName_Source_Other                 0
ContinentName_Destination_Europe           0
ContinentName_Destination_North America    0
ContinentName_Destination_Other            0
ContinentName_Proxy_North America          0
ContinentName_Proxy_Other                  0
ContinentName_Proxy_noProxy                0
Source IP_Class_B                          0
Source IP_Class_C                          0
Destination IP_Class_B                     0
Destination IP_Class_C                     0
Proxy_Class_B                              0
Proxy_Class_C                              0
Proxy_Class_noProxy                        0
Source Port_Cat_Registered                 0
Destination Port_Cat_Registered            0
Browser_family_Firefox                     0
Browser_family_IE                          0
Browser_family_Opera                       0
Browser_family_Other                       0
Browser_family_Safari                      0
OS_family_Linux                            0
OS_family_Mac OS X                         0
OS_family_Windows                          0
OS_family_iOS                              0
Device_type_PC                             0
Device_type_Tablet                         0
Device_type_Unknown                        0
dtype: int64

### SPLIT 1 : Completely random (not stratisfied) - 80/20

In [7]:
df_train, df_test = train_test_split(df, test_size=0.2, random_state=777)

In [8]:
len(df), len(df_train), len(df_test)

(40000, 32000, 8000)

In [9]:
print(df['Attack Type'].value_counts())
print(df_train['Attack Type'].value_counts())
print(df_test['Attack Type'].value_counts())

Attack Type
1    13428
3    13307
2    13265
Name: count, dtype: int64
Attack Type
1    10708
2    10670
3    10622
Name: count, dtype: int64
Attack Type
1    2720
3    2685
2    2595
Name: count, dtype: int64

In [10]:
df_train.columns

Index(['Attack Type', 'Severity Level', 'Packet Length_Quartile',
       'Anomaly Scores_Quartile', 'Packet Type_Data', 'Malware Indicators_1',
       'Alerts/Warnings_1', 'Attack Signature_Known Pattern B',
       'Firewall Logs_1', 'IDS/IPS Alerts_1', 'Log Source_Server',
       'is_weekend_1', 'Protocol_TCP', 'Protocol_UDP', 'Traffic Type_FTP',
       'Traffic Type_HTTP', 'Action Taken_Ignored', 'Action Taken_Logged',
       'Network Segment_Segment B', 'Network Segment_Segment C',
       'hours_div_6-20', 'ContinentName_Source_Europe',
       'ContinentName_Source_North America', 'ContinentName_Source_Other',
       'ContinentName_Destination_Europe',
       'ContinentName_Destination_North America',
       'ContinentName_Destination_Other', 'ContinentName_Proxy_North America',
       'ContinentName_Proxy_Other', 'ContinentName_Proxy_noProxy',
       'Source IP_Class_B', 'Source IP_Class_C', 'Destination IP_Class_B',
       'Destination IP_Class_C', 'Proxy_Class_B', 'Proxy_Class_C',
       'Proxy_Class_noProxy', 'Source Port_Cat_Registered',
       'Destination Port_Cat_Registered', 'Browser_family_Firefox',
       'Browser_family_IE', 'Browser_family_Opera', 'Browser_family_Other',
       'Browser_family_Safari', 'OS_family_Linux', 'OS_family_Mac OS X',
       'OS_family_Windows', 'OS_family_iOS', 'Device_type_PC',
       'Device_type_Tablet', 'Device_type_Unknown'],
      dtype='object')

In [11]:
# get the values of the columns for the training data
X_train = df_train.loc[:,['Protocol_TCP', 'Protocol_UDP', 'Packet Type_Data', 'Traffic Type_FTP',
       'Traffic Type_HTTP', 'Malware Indicators_1', 'Alerts/Warnings_1','Attack Signature_Known Pattern B',
       'Action Taken_Ignored', 'Action Taken_Logged', 'Severity Level',
       'Network Segment_Segment B', 'Network Segment_Segment C',
       'Firewall Logs_1', 'IDS/IPS Alerts_1', 'Log Source_Server',
       'is_weekend_1', 'hours_div_6-20', 'ContinentName_Source_Europe',
       'ContinentName_Source_North America', 'ContinentName_Source_Other',
       'ContinentName_Destination_Europe',
       'ContinentName_Destination_North America',
       'ContinentName_Destination_Other', 'ContinentName_Proxy_North America',
       'ContinentName_Proxy_Other', 'ContinentName_Proxy_noProxy',
       'Source IP_Class_B', 'Source IP_Class_C', 'Destination IP_Class_B',
       'Destination IP_Class_C', 'Proxy_Class_B', 'Proxy_Class_C',
       'Proxy_Class_noProxy', 'Source Port_Cat_Registered',
       'Destination Port_Cat_Registered', 'Packet Length_Quartile',
       'Anomaly Scores_Quartile', 'Browser_family_Firefox',
       'Browser_family_IE', 'Browser_family_Opera', 'Browser_family_Other',
       'Browser_family_Safari', 'OS_family_Linux', 'OS_family_Mac OS X',
       'OS_family_Windows', 'OS_family_iOS', 'Device_type_PC',
       'Device_type_Tablet', 'Device_type_Unknown']].values
y_train = df_train['Attack Type'].values

In [12]:
# get the values of the columns for the testing data
X_test = df_test.loc[:,['Protocol_TCP', 'Protocol_UDP', 'Packet Type_Data', 'Traffic Type_FTP',
       'Traffic Type_HTTP', 'Malware Indicators_1', 'Alerts/Warnings_1','Attack Signature_Known Pattern B',
       'Action Taken_Ignored', 'Action Taken_Logged', 'Severity Level',
       'Network Segment_Segment B', 'Network Segment_Segment C',
       'Firewall Logs_1', 'IDS/IPS Alerts_1', 'Log Source_Server',
       'is_weekend_1', 'hours_div_6-20', 'ContinentName_Source_Europe',
       'ContinentName_Source_North America', 'ContinentName_Source_Other',
       'ContinentName_Destination_Europe',
       'ContinentName_Destination_North America',
       'ContinentName_Destination_Other', 'ContinentName_Proxy_North America',
       'ContinentName_Proxy_Other', 'ContinentName_Proxy_noProxy',
       'Source IP_Class_B', 'Source IP_Class_C', 'Destination IP_Class_B',
       'Destination IP_Class_C', 'Proxy_Class_B', 'Proxy_Class_C',
       'Proxy_Class_noProxy', 'Source Port_Cat_Registered',
       'Destination Port_Cat_Registered', 'Packet Length_Quartile',
       'Anomaly Scores_Quartile', 'Browser_family_Firefox',
       'Browser_family_IE', 'Browser_family_Opera', 'Browser_family_Other',
       'Browser_family_Safari', 'OS_family_Linux', 'OS_family_Mac OS X',
       'OS_family_Windows', 'OS_family_iOS', 'Device_type_PC',
       'Device_type_Tablet', 'Device_type_Unknown']].values
y_test = df_test['Attack Type'].values

### MODEL 1 : Logistic Regression (linear)

In [13]:
from sklearn.linear_model import LogisticRegression

In [14]:
# Initialize the model
lr_model = LogisticRegression(random_state=0, max_iter=1000)

In [15]:
# Train the model on the training data
lr_model.fit(X=X_train, y=y_train)

LogisticRegression(max_iter=1000, random_state=0)

In [16]:
y_test_predicted = lr_model.predict(X_test)

In [17]:
y_test_predicted

array([2, 3, 1, ..., 2, 2, 2], shape=(8000,))

In [18]:
y_test

array([3, 1, 2, ..., 1, 3, 1], shape=(8000,))

In [19]:
# Check % of correct predictions
# CONCLUSION : NOT GOOD !!!, only 33.6% correct predictionss
(y_test_predicted == y_test).sum()/len(y_test)

np.float64(0.33625)

In [20]:
from sklearn.metrics import confusion_matrix

In [21]:
cf = pd.DataFrame(
    columns=["y_test_Malware","y_test_Intrusion", "y_test_DDos"],index=["y_pred_Malware","y_pred_Intrusion", "y_pred_DDos"]
)

In [22]:
cf.loc[:,:] = confusion_matrix(y_true= y_test,y_pred= y_test_predicted)

In [23]:
# numbers of correct prediction (diagonal values)
cf

                 y_test_Malware y_test_Intrusion y_test_DDos
y_pred_Malware              940              908         872
y_pred_Intrusion            921              893         781
y_pred_DDos                 953              875         857

In [24]:
cf/len(y_test)

                 y_test_Malware y_test_Intrusion y_test_DDos
y_pred_Malware           0.1175           0.1135       0.109
y_pred_Intrusion       0.115125         0.111625    0.097625
y_pred_DDos            0.119125         0.109375    0.107125

In [25]:
from sklearn.metrics import recall_score, precision_score

In [26]:
from sklearn.metrics import recall_score, precision_score

# Calculate recall with different averaging methods
recall_macro = recall_score(y_true=y_test, y_pred=y_test_predicted, average='macro')
print("Recall (macro):", recall_macro)
# recall_weighted = recall_score(y_true=y_test, y_pred=y_test_predicted, average='weighted')

# Calculate precision with different averaging methods
precision_macro = precision_score(y_true=y_test, y_pred=y_test_predicted, average='macro')
print("Precision (macro):", precision_macro)        
# precision_weighted = precision_score(y_true=y_test, y_pred=y_test_predicted, average='weighted')

Recall (macro): 0.33629739416891397
Precision (macro): 0.33639511791553917

In [27]:
# Get scores for each class individually
recall_per_class = recall_score(y_true=y_test, y_pred=y_test_predicted, average=None)
precision_per_class = precision_score(y_true=y_test, y_pred=y_test_predicted, average=None)

classes = np.unique(y_test)
for i, cls in enumerate(classes):
    print(f"{cls}:")
    print(f"  Recall:    {recall_per_class[i]:.4f}")
    print(f"  Precision: {precision_per_class[i]:.4f}")

1:
  Recall:    0.3456
  Precision: 0.3340
2:
  Recall:    0.3441
  Precision: 0.3337
3:
  Recall:    0.3192
  Precision: 0.3414

In [28]:
from sklearn.metrics import classification_report

In [29]:
report = classification_report(y_true=y_test, y_pred=y_test_predicted)
print(report)

              precision    recall  f1-score   support

           1       0.33      0.35      0.34      2720
           2       0.33      0.34      0.34      2595
           3       0.34      0.32      0.33      2685

    accuracy                           0.34      8000
   macro avg       0.34      0.34      0.34      8000
weighted avg       0.34      0.34      0.34      8000

### MODEL 2 : Decision Tree (non-linear)

In [30]:
from sklearn.tree import DecisionTreeClassifier

In [31]:
dt_model = DecisionTreeClassifier(random_state=0)

In [32]:
dt_model.fit(X=X_train,y=y_train)

DecisionTreeClassifier(random_state=0)

In [33]:
y_test_predicted_dt = dt_model.predict(X_test)

In [34]:
report_dt = classification_report(y_pred=y_test_predicted_dt,y_true=y_test)
print(report_dt)

              precision    recall  f1-score   support

           1       0.33      0.33      0.33      2720
           2       0.33      0.33      0.33      2595
           3       0.34      0.34      0.34      2685

    accuracy                           0.33      8000
   macro avg       0.33      0.33      0.33      8000
weighted avg       0.33      0.33      0.33      8000

### MODEL 3 : Random Forest (non-linear)

In [35]:
from sklearn.ensemble import RandomForestClassifier

In [36]:
rf_model = RandomForestClassifier(random_state=0)

In [37]:
rf_model.fit(X=X_train,y=y_train)

RandomForestClassifier(random_state=0)

In [38]:
y_test_predicted_rf = rf_model.predict(X_test)

In [39]:
report_rf = classification_report(y_pred=y_test_predicted_rf,y_true=y_test)
print(report_rf)

              precision    recall  f1-score   support

           1       0.34      0.36      0.35      2720
           2       0.31      0.31      0.31      2595
           3       0.32      0.30      0.31      2685

    accuracy                           0.32      8000
   macro avg       0.32      0.32      0.32      8000
weighted avg       0.32      0.32      0.32      8000

### MODEL 4 : Multi-Layer Perceptron / MLP (non-linear)

In [40]:
from sklearn.neural_network import MLPClassifier

In [41]:
X_train.shape

(32000, 50)

In [42]:
# mlp_model 1, rule of thumb: Start with (n_featurs + n_classes) / 2 = (50+3)/2 = 27
mlp_model = MLPClassifier(hidden_layer_sizes=(27,15),max_iter=1000, random_state=0)
mlp_model.fit(X=X_train, y=y_train)
y_test_predicted_mlp = mlp_model.predict(X_test)
report_mlp = classification_report(y_true=y_test, y_pred=y_test_predicted_mlp)
print(report_mlp)

              precision    recall  f1-score   support

           1       0.35      0.27      0.31      2720
           2       0.33      0.38      0.35      2595
           3       0.33      0.36      0.35      2685

    accuracy                           0.34      8000
   macro avg       0.34      0.34      0.33      8000
weighted avg       0.34      0.34      0.33      8000

In [43]:
# mlp_model 2, More complex, 3 layers
mlp_model2 = MLPClassifier(hidden_layer_sizes=(100,50,25),max_iter=1000, random_state=0)
mlp_model2.fit(X=X_train, y=y_train)
y_test_predicted_mlp2 = mlp_model2.predict(X_test)
report_mlp2 = classification_report(y_true=y_test, y_pred=y_test_predicted_mlp2)
print(report_mlp2)

              precision    recall  f1-score   support

           1       0.34      0.31      0.32      2720
           2       0.33      0.32      0.32      2595
           3       0.33      0.37      0.35      2685

    accuracy                           0.33      8000
   macro avg       0.33      0.33      0.33      8000
weighted avg       0.33      0.33      0.33      8000

### Model 5: XGBoost

In [44]:
import xgboost as xgb
from sklearn.metrics import classification_report
from sklearn.preprocessing import LabelEncoder

# Encode target labels for XGBoost
label_encoder = LabelEncoder()
y_train_encoded = label_encoder.fit_transform(y_train)
y_test_encoded = label_encoder.transform(y_test)

print("Label mapping:")
for i, label in enumerate(label_encoder.classes_):
    print(f"  {label} -> {i}")

# XGBoost Model
xgb_model = xgb.XGBClassifier(
    n_estimators=200,
    max_depth=6,
    learning_rate=0.1,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=0,
    eval_metric='mlogloss'
)

# Train with encoded labels
xgb_model.fit(X_train, y_train_encoded)

# Predict (returns numeric labels)
y_test_predicted_xgb_encoded = xgb_model.predict(X_test)

# Convert predictions back to original labels
y_test_predicted_xgb = label_encoder.inverse_transform(y_test_predicted_xgb_encoded)

# Evaluate with original string labels
report_xgb = classification_report(y_true=y_test, y_pred=y_test_predicted_xgb)
print("XGBoost Results:")
print(report_xgb)

Label mapping:
  1 -> 0
  2 -> 1
  3 -> 2
XGBoost Results:
              precision    recall  f1-score   support

           1       0.34      0.34      0.34      2720
           2       0.33      0.34      0.34      2595
           3       0.33      0.32      0.33      2685

    accuracy                           0.33      8000
   macro avg       0.33      0.33      0.33      8000
weighted avg       0.33      0.33      0.33      8000